using System.ComponentModel;

namespace Vanish.Helpers;

// TR/EN strings with live switching.
// xaml: Text="{h:L Nav_AllApps}" or {Binding [Nav_AllApps], Source={x:Static h:Loc.I}}
// raising "Item[]" refreshes all indexer bindings when the language changes
public sealed class Loc : INotifyPropertyChanged
{
    public static Loc I { get; } = new();

    public event PropertyChangedEventHandler? PropertyChanged;

    private string _lang = "tr";

    // "tr" or "en"
    public string Language
    {
        get => _lang;
        set
        {
            var v = (value ?? "tr").ToLowerInvariant();
            if (v != "tr" && v != "en") v = "en";
            if (_lang == v) return;
            _lang = v;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Language)));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(IsTurkish)));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(IsEnglish)));
        }
    }

    public bool IsTurkish => _lang == "tr";
    public bool IsEnglish => _lang == "en";

    public void Toggle() => Language = _lang == "tr" ? "en" : "tr";

    // localized lookup. falls back to English, then to the key itself
    public string this[string key]
    {
        get
        {
            var table = _lang == "tr" ? Tr : En;
            if (table.TryGetValue(key, out var v)) return v;
            return En.TryGetValue(key, out var en) ? en : key;
        }
    }

    // direct (non-binding) lookup helper for code-behind / view-models
    public string T(string key) => this[key];

    private static readonly Dictionary<string, string> Tr = new()
    {
        ["About_Copyright"] = "© 2026 ANIL GÜL · Tüm hakları saklıdır.",
        ["About_New1"] = "Gereksiz dosya temizleyici yenilendi: hiçbir şey otomatik seçilmez, her kategori açılıp silinecekler tek tek görülür.",
        ["About_New2"] = "Yeni Sistem İzleyici: işlemci, bellek, sıcaklık, disk, ağ, pil ve en çok kaynak kullanan işlemler — canlı.",
        ["About_New3"] = "Daha güvenli kalıntı taraması: Microsoft ve paylaşılan klasörler korunur, kalıntılar asla otomatik seçilmez.",
        ["About_New4"] = "Yeni araçlar: büyük dosyalar, dosya parçalayıcı, geçmiş ve gizlilik, kanıt temizleyici, yedek yöneticisi.",
        ["About_New5"] = "Başlangıç programlarını silmeden kapatıp açabilirsiniz (Görev Yöneticisi ile aynı yöntem).",
        ["About_New6"] = "Koyu / açık / sistem teması, akıcı animasyonlar ve çok daha hızlı açılış.",
        ["About_New7"] = "Avcı modunda nişangâh: herhangi bir pencerenin üzerine sürükleyip programını bulun.",
        ["About_Releases"] = "Sürümler",
        ["About_Repo"] = "Projeyi incele",
        ["About_Role"] = "Oblivion'un tasarımcısı ve geliştiricisi",
        ["About_VersionFmt"] = "Sürüm {0}",
        ["About_WhatsNew"] = "Yenilikler",

        ["Act_Cancel"] = "İptal",
        ["Act_Clean"] = "Temizle",
        ["Act_Clear"] = "Temizle",
        ["Act_ClearList"] = "Listeyi temizle",
        ["Act_Close"] = "Kapat",
        ["Act_Delete"] = "Sil",
        ["Act_DeleteSelected"] = "Seçilenleri sil",
        ["Act_EndTask"] = "Görevi sonlandır",
        ["Act_ForceUninstall"] = "Zorla kaldır",
        ["Act_MoveToRecycle"] = "Geri Dönüşüm Kutusu'na taşı",
        ["Act_Open"] = "Aç",
        ["Act_OtherCommands"] = "Diğer komutlar",
        ["Act_Refresh"] = "Yenile",
        ["Act_Remove"] = "Kaldır",
        ["Act_Restore"] = "Geri yükle",
        ["Act_SelectAll"] = "Tümünü seç",
        ["Act_SelectNone"] = "Seçimi kaldır",
        ["Act_ShowLocation"] = "Konumu göster",
        ["Act_Shred"] = "Kalıcı olarak yok et",
        ["Act_Stop"] = "Durdur",
        ["Act_Uninstall"] = "Kaldır",

        ["App_PerUser"] = "kullanıcı",
        ["App_Tagline"] = "Kaldır · Temizle · İzle",
        ["App_UnknownPublisher"] = "Bilinmeyen yayıncı",

        ["Apps_Architecture"] = "Mimari",
        ["Apps_FilterAll"] = "Tümü",
        ["Apps_FilterLarge"] = "Büyük",
        ["Apps_FilterRecent"] = "Son 30 gün",
        ["Apps_InstallDate"] = "Kurulum",
        ["Apps_Loading"] = "Yüklü programlar okunuyor…",
        ["Apps_Location"] = "Konum",
        ["Apps_Name"] = "Ad",
        ["Apps_NoMatch"] = "Eşleşen program yok",
        ["Apps_NoMatchText"] = "Aramayı ya da filtreyi değiştirmeyi deneyin.",
        ["Apps_ProgramsWord"] = "program",
        ["Apps_Publisher"] = "Yayıncı",
        ["Apps_RegistryKey"] = "Kayıt anahtarı",
        ["Apps_Search"] = "Program veya yayıncı ara  (Ctrl+F)",
        ["Apps_SelectHint"] = "Listeden bir program seçin",
        ["Apps_Size"] = "Boyut",
        ["Apps_SortPublisher"] = "Yayıncı",
        ["Apps_Subtitle"] = "Bir program seçip kaldırın; geride kalanları siz onaylayarak temizleyin.",
        ["Apps_UninstallCommand"] = "Kaldırma komutu",
        ["Apps_Version"] = "Sürüm",

        ["Backup_CreatePoint"] = "Geri yükleme noktası oluştur",
        ["Backup_DeleteText"] = "Bu yedek dosyası silinecek. Kayıt defterinde hiçbir değişiklik yapılmaz.",
        ["Backup_DeleteTitle"] = "Yedek silinsin mi?",
        ["Backup_ManualPointName"] = "Oblivion — elle oluşturulan nokta",
        ["Backup_NoPointsText"] = "Sistem Geri Yükleme kapalı olabilir ya da henüz bir nokta yok.",
        ["Backup_NoPointsTitle"] = "Geri yükleme noktası yok",
        ["Backup_NoneText"] = "Oblivion kayıt defterinden bir şey sildiğinde önce buraya yedek alır.",
        ["Backup_NoneTitle"] = "Henüz yedek yok",
        ["Backup_OpenFolder"] = "Yedek klasörü",
        ["Backup_OpenRestore"] = "Sistem Geri Yükleme",
        ["Backup_PointCreated"] = "Geri yükleme noktası oluşturuldu.",
        ["Backup_PointFailed"] = "Geri yükleme noktası oluşturulamadı. Sistem Geri Yükleme kapalı olabilir.",
        ["Backup_RestoreFailed"] = "Yedek geri yüklenemedi.",
        ["Backup_RestoreText"] = "Bu .reg yedeği kayıt defterine geri yazılacak; silinen anahtar ve değerler eski hâline döner.",
        ["Backup_RestoreTitle"] = "Yedek geri yüklensin mi?",
        ["Backup_Restored"] = "Yedek geri yüklendi.",
        ["Backup_Subtitle"] = "Silmeden önce alınan kayıt defteri yedekleri ve Windows geri yükleme noktaları.",
        ["Backup_TabRegistry"] = "Kayıt defteri yedekleri",
        ["Backup_TabRestore"] = "Geri yükleme noktaları",

        ["Badge_New"] = "YENİ",

        ["Cmd_Copied"] = "Ayrıntılar panoya kopyalandı.",
        ["Cmd_CopyDetails"] = "Ayrıntıları kopyala",
        ["Cmd_CopyFailed"] = "Panoya kopyalanamadı.",
        ["Cmd_EntryRemoved"] = "Kayıt girdisi listeden kaldırıldı (yedeği alındı).",
        ["Cmd_NoInstallFolder"] = "Kurulum klasörü bulunamadı.",
        ["Cmd_NoWebsite"] = "Yayıncının web sitesi kayıtlı değil.",
        ["Cmd_OpenInstallFolder"] = "Kurulum klasörünü aç",
        ["Cmd_OpenRegistry"] = "Kayıt defterinde aç",
        ["Cmd_OpenWebsite"] = "Yayıncının web sitesi",
        ["Cmd_RemoveEntry"] = "Listeden kaldır (bozuk girdi)",
        ["Cmd_RemoveEntryText"] = "Programın dosyalarına dokunulmaz; yalnızca kaldırma kaydı silinir (önce yedeklenir). Kaldırıcısı artık çalışmayan bozuk girdiler için kullanın.",
        ["Cmd_RemoveEntryTitleFmt"] = "\"{0}\" listeden kaldırılsın mı?",
        ["Cmd_SearchWeb"] = "İnternette ara",

        ["Conf_High"] = "Kesin",
        ["Conf_Low"] = "Düşük",
        ["Conf_Medium"] = "Olası",

        ["Dash_AllLogs"] = "Tüm kayıtlar",
        ["Dash_Extensions"] = "Tarayıcı eklentisi",
        ["Dash_ExtensionsDetailFmt"] = "{0} tarayıcıda",
        ["Dash_GreetDay"] = "İyi günler",
        ["Dash_GreetEvening"] = "İyi akşamlar",
        ["Dash_GreetMorning"] = "Günaydın",
        ["Dash_GreetNight"] = "İyi geceler",
        ["Dash_Health"] = "SİSTEM DURUMU",
        ["Dash_NoActivity"] = "Henüz bir işlem yapılmadı.",
        ["Dash_Programs"] = "Yüklü program",
        ["Dash_QuickActions"] = "Hızlı işlemler",
        ["Dash_RecentActivity"] = "Son işlemler",
        ["Dash_Startup"] = "Açılışta çalışan",
        ["Dash_StartupDetailFmt"] = "{0} açık · toplam {1}",
        ["Dash_StoreApps"] = "Windows uygulaması",
        ["Dash_StoreAppsDetail"] = "Microsoft Store / MSIX",
        ["Dash_Subtitle"] = "Sisteminize genel bakış — her şey tek ekranda.",
        ["Dash_TotalSizeFmt"] = "Toplam {0}",

        ["Done_BackToList"] = "Listeye dön",
        ["Done_Cleaned"] = "Seçtiğiniz kalıntılar temizlendi.",
        ["Done_FailedFmt"] = "{0} öğe kullanımda olduğu ya da korunduğu için silinmedi.",
        ["Done_ItemsRemoved"] = "öğe silindi",
        ["Done_NoLeftovers"] = "Kalıntı bulunamadı — sistem tertemiz.",
        ["Done_Skipped"] = "Kalıntılar silinmeden bırakıldı.",
        ["Done_SpaceFreed"] = "yer açıldı",
        ["Done_TitleFmt"] = "{0} kaldırıldı",
        ["Done_ToastFmt"] = "{0} kalıntı silindi · {1} boşaltıldı",

        ["Evid_ChooseDrive"] = "Sürücü seçin",
        ["Evid_ConfirmText"] = "Sürücüdeki boş alanın tamamı üç geçişte (0x00, 0xFF, rastgele) üzerine yazılacak. Mevcut dosyalarınıza dokunulmaz. Büyük disklerde uzun sürebilir; bu sırada disk geçici olarak dolu görünür.",
        ["Evid_ConfirmTitleFmt"] = "{0} sürücüsündeki boş alan temizlensin mi?",
        ["Evid_Done"] = "Tamamlandı — silinmiş dosyalar artık kurtarılamaz.",
        ["Evid_DoneFmt"] = "{0} boş alanı temizlendi.",
        ["Evid_Elapsed"] = "Geçen süre",
        ["Evid_Explain"] = "Silinen dosyalar diskte iz bırakır ve kurtarma programlarıyla geri getirilebilir. Kanıt temizleyici yalnızca BOŞ alanın üzerine yazar; var olan dosyalarınız olduğu gibi kalır. Windows'un kendi aracı (cipher /w) kullanılır.",
        ["Evid_Failed"] = "Boş alan temizlenemedi.",
        ["Evid_Free"] = "Boş",
        ["Evid_Pass1"] = "1. geçiş · sıfırlar",
        ["Evid_Pass2"] = "2. geçiş · birler",
        ["Evid_Pass3"] = "3. geçiş · rastgele",
        ["Evid_PassFmt"] = "{0}. geçiş yazılıyor…",
        ["Evid_Preparing"] = "Hazırlanıyor…",
        ["Evid_SsdNote"] = "Bu bir SSD. SSD'ler silinen verileri TRIM ile zaten temizler; bu işlem çoğunlukla gereksizdir ve diske fazladan yazma yapar.",
        ["Evid_Start"] = "Boş alanı temizle",
        ["Evid_Subtitle"] = "Daha önce silinmiş dosyaların kurtarılmasını engeller.",

        ["Ext_AllBrowsers"] = "Tümü",
        ["Ext_None"] = "Eklenti bulunamadı",
        ["Ext_NoneText"] = "Edge, Chrome, Brave, Vivaldi, Opera ve Firefox tarandı.",
        ["Ext_RemoveManyTitleFmt"] = "{0} eklenti kaldırılsın mı?",
        ["Ext_RemoveOneTitleFmt"] = "\"{0}\" kaldırılsın mı?",
        ["Ext_RemoveSelected"] = "Seçilenleri kaldır",
        ["Ext_RemoveText"] = "Eklenti dosyaları Geri Dönüşüm Kutusu'na taşınır. Tarayıcı açıksa, kapatıp yeniden açtığınızda eklenti kaybolur.",
        ["Ext_RemovedFmt"] = "{0} eklenti kaldırıldı.",
        ["Ext_RunningFmt"] = "Açık tarayıcılar: {0}. Eklenti kaldırmadan önce kapatmanız önerilir.",
        ["Ext_Search"] = "Eklenti ara",
        ["Ext_SelectedWord"] = "eklenti seçili",
        ["Ext_Subtitle"] = "Tüm tarayıcılardaki eklentiler tek listede. Hiçbiri otomatik seçilmez.",

        ["Health_Attention"] = "Biraz ilgi istiyor",
        ["Health_AttentionText"] = "Aşağıdaki önerilerle sisteminizi rahatlatabilirsiniz.",
        ["Health_Good"] = "İyi durumda",
        ["Health_GoodText"] = "Birkaç küçük iyileştirme yapılabilir.",
        ["Health_Great"] = "Mükemmel durumda",
        ["Health_GreatText"] = "Sisteminiz hızlı ve düzenli görünüyor.",

        ["Hunter_BelongsToFmt"] = "Bu pencere \"{0}\" programına ait.",
        ["Hunter_DragHere"] = "Nişangâhı bir pencereye sürükleyin",
        ["Hunter_DragHint"] = "Basılı tutun, hedef pencerenin üzerine götürün ve bırakın.",
        ["Hunter_DragTip"] = "Basılı tutup sürükleyin",
        ["Hunter_EndText"] = "Programdaki kaydedilmemiş veriler kaybolabilir.",
        ["Hunter_NotInstalledProgram"] = "Yüklü programlar arasında karşılığı bulunamadı (taşınabilir ya da Windows'un bir parçası olabilir).",
        ["Hunter_Running"] = "Açık pencereler",
        ["Hunter_Subtitle"] = "Bir pencerenin hangi programa ait olduğunu bulun ve tek tıkla kaldırın.",

        ["Junk_Browser"] = "Tarayıcı önbellekleri",
        ["Junk_Browser_D"] = "Edge, Chrome, Brave, Vivaldi, Opera ve Firefox önbellekleri. Şifreler, yer imleri ve geçmiş SİLİNMEZ.",
        ["Junk_Browser_Note"] = "Tarayıcı açıksa kullanımdaki dosyalar atlanır; sayfalar ilk açılışta biraz daha yavaş yüklenebilir.",
        ["Junk_CleanSelected"] = "Seçilenleri temizle",
        ["Junk_Cleaning"] = "Temizleniyor…",
        ["Junk_ConfirmBinNote"] = "Geri Dönüşüm Kutusu boşaltılacak — bu geri alınamaz.",
        ["Junk_ConfirmDeleteNote"] = "Geçici dosyalar ve önbellekler kalıcı olarak silinir; kullanımda olanlar atlanır.",
        ["Junk_ConfirmRecycleNote"] = "İndirilen kurulum dosyaları Geri Dönüşüm Kutusu'na taşınır; oradan geri alınabilir.",
        ["Junk_ConfirmTitleFmt"] = "{0} temizlensin mi?",
        ["Junk_Crash"] = "Hata raporları ve döküm dosyaları",
        ["Junk_Crash_D"] = "Windows hata raporları, uygulama çökme dökümleri ve MEMORY.DMP.",
        ["Junk_ExpandAll"] = "Tümünü aç / kapat",
        ["Junk_ExpandAllTip"] = "Tüm kategorilerin içeriğini göster",
        ["Junk_Found"] = "Bulunan",
        ["Junk_Freed"] = "boşaltıldı",
        ["Junk_GroupDetail"] = "Küçük dosyaların toplamı",
        ["Junk_GroupFmt"] = "… ve {0} öğe daha",
        ["Junk_Installers"] = "İndirilen kurulum dosyaları",
        ["Junk_Installers_D"] = "İndirilenler klasöründeki kurulum (.exe, .msi, .msix) dosyaları.",
        ["Junk_Installers_Note"] = "Bunlar sizin dosyalarınızdır: kalıcı silinmez, Geri Dönüşüm Kutusu'na taşınır.",
        ["Junk_ItemsFmt"] = "{0} öğe",
        ["Junk_Nothing"] = "Temiz",
        ["Junk_NothingSelected"] = "Hiçbir şey seçilmedi",
        ["Junk_RecycleBin"] = "Geri Dönüşüm Kutusu",
        ["Junk_RecycleBin_D"] = "Daha önce sildiğiniz dosyalar.",
        ["Junk_RecycleBin_Note"] = "Boşaltılınca geri alınamaz.",
        ["Junk_Rescan"] = "Yeniden tara",
        ["Junk_ResultFmt"] = "{0} öğe silindi.",
        ["Junk_ResultSkippedFmt"] = "{0} öğe silindi, kullanımda olan {1} öğe atlandı.",
        ["Junk_Scanning"] = "Taranıyor…",
        ["Junk_SelectCategoryTip"] = "Bu kategorideki her şeyi seç / bırak",
        ["Junk_Selected"] = "Seçili",
        ["Junk_SelectedFmt"] = "Seçili: {0}",
        ["Junk_SelectedTotalFmt"] = "{0} öğe · {1}",
        ["Junk_ShowItems"] = "Silinecekleri göster",
        ["Junk_Subtitle"] = "Hiçbir şey otomatik seçilmez. Bir kategoriyi açın, silinecekleri tek tek görün ve kendiniz işaretleyin.",
        ["Junk_Thumbs"] = "Küçük resim ve simge önbelleği",
        ["Junk_Thumbs_D"] = "Dosya Gezgini'nin küçük resim (thumbcache) ve simge önbellek dosyaları.",
        ["Junk_Thumbs_Note"] = "Windows bunları gerektiğinde yeniden oluşturur; Gezgin açıkken bazıları atlanabilir.",
        ["Junk_ToastFmt"] = "{0} yer açıldı",
        ["Junk_Update"] = "Windows Update indirmeleri",
        ["Junk_Update_D"] = "Kurulmuş güncellemelerin indirme dosyaları (SoftwareDistribution\\Download).",
        ["Junk_Update_Note"] = "Bekleyen bir güncelleme varsa Windows dosyaları yeniden indirir.",
        ["Junk_UserTemp"] = "Kullanıcı geçici dosyaları",
        ["Junk_UserTemp_D"] = "Programların %TEMP% klasöründe bıraktığı geçici dosyalar.",
        ["Junk_WinTemp"] = "Windows geçici dosyaları",
        ["Junk_WinTemp_D"] = "Windows\\Temp klasöründeki geçici dosyalar.",

        ["Large_Drive"] = "Yerel Disk",
        ["Large_EmptyText"] = "Bir konum ve en küçük boyutu seçip Tara'ya basın. Windows, program ve AppData klasörleri hiç taranmaz.",
        ["Large_EmptyTitle"] = "Yer kaplayan dosyaları bulun",
        ["Large_FoundFmt"] = "{0} dosya bulundu · toplam {1}",
        ["Large_MinSize"] = "En küçük boyut",
        ["Large_NoneFmt"] = "{0} üzerinde dosya bulunamadı.",
        ["Large_PickFolder"] = "Klasör seç",
        ["Large_RecycleText"] = "Dosyalar Geri Dönüşüm Kutusu'na taşınır; gerekirse oradan geri alabilirsiniz.",
        ["Large_RecycleTitleFmt"] = "{0} dosya ({1}) Geri Dönüşüm Kutusu'na taşınsın mı?",
        ["Large_RecycledFmt"] = "{0} dosya taşındı · {1} boşaltıldı",
        ["Large_Scan"] = "Tara",
        ["Large_ScannedFmt"] = "{0} dosya incelendi…",
        ["Large_SelectedFmt"] = "{0} dosya seçili · {1}",
        ["Large_Starting"] = "Başlıyor…",
        ["Large_Subtitle"] = "Diskinizde en çok yer kaplayan kişisel dosyalar. Hiçbiri otomatik seçilmez.",
        ["Large_UserFolder"] = "Kullanıcı klasörüm",
        ["Large_Where"] = "Nerede aransın?",

        ["Left_All"] = "Tümü",
        ["Left_DeleteTextPermanent"] = "Dosyalar kalıcı olarak silinir. Kayıt defteri öğelerinin önce yedeği alınır (Yedek yöneticisinden geri yüklenebilir).",
        ["Left_DeleteTextRecycle"] = "Dosya ve klasörler Geri Dönüşüm Kutusu'na taşınır. Kayıt defteri öğelerinin önce yedeği alınır (Yedek yöneticisinden geri yüklenebilir).",
        ["Left_DeleteTitleFmt"] = "{0} kalıntı silinsin mi?",
        ["Left_Explain"] = "Hiçbir kalıntı otomatik seçilmez. Her satırda neden bulunduğu ve ne kadar emin olduğumuz yazar: \"Kesin\" olanlar programın kendi klasör ve kayıtlarıdır, \"Düşük\" olanları dikkatle inceleyin. Windows ve Microsoft konumları hiç listelenmez.",
        ["Left_Files"] = "Dosyalar",
        ["Left_Finish"] = "Silmeden bitir",
        ["Left_FoundFor"] = "Kalıntılar:",
        ["Left_LowWarningFmt"] = "Dikkat: {0} öğe düşük güvenle eşleşti. Yalnızca emin olduğunuzda silin.",
        ["Left_NoneSelected"] = "Silinecek öğe seçilmedi",
        ["Left_Registry"] = "Kayıt defteri",
        ["Left_SelectSafe"] = "Kesin olanları seç",
        ["Left_SelectSafeTip"] = "Yalnızca kesin eşleşmeleri seçer",
        ["Left_SelectedFmt"] = "{0} öğe seçili · {1}",
        ["Left_StillInstalled"] = "Program hâlâ yüklü görünüyor. Bu öğeler çalışan programa ait olabilir — silmeden önce iyice kontrol edin.",
        ["Left_SummaryFmt"] = "{0} öğe bulundu · {1}",

        ["Live_BatteryChargingFmt"] = "Pil %{0} · şarj oluyor",
        ["Live_BatteryFmt"] = "Pil %{0}",
        ["Live_Cpu"] = "İşlemci",
        ["Live_Details"] = "Ayrıntılar",
        ["Live_Disk"] = "Disk",
        ["Live_DiskFreeFmt"] = "{0} boş / {1}",
        ["Live_Network"] = "Ağ",
        ["Live_Ram"] = "Bellek",
        ["Live_TempNA"] = "sensör yok",
        ["Live_Title"] = "Canlı sistem",

        ["Log_Backup"] = "Geri yükleme noktası oluşturuldu",
        ["Log_Baseline"] = "Kurulum izleyici: görüntü alındı",
        ["Log_EndTask"] = "Görev sonlandırıldı",
        ["Log_EntryRemoved"] = "Bozuk girdi kaldırıldı",
        ["Log_Evidence"] = "Boş alan temizlendi",
        ["Log_Extension"] = "Tarayıcı eklentisi kaldırıldı",
        ["Log_Forced"] = "Zorla kaldırıldı",
        ["Log_History"] = "Geçmiş temizlendi",
        ["Log_Junk"] = "Gereksiz dosyalar temizlendi",
        ["Log_JunkDetailFmt"] = "{0} boşaltıldı · {1} öğe",
        ["Log_LargeFiles"] = "Büyük dosyalar taşındı",
        ["Log_LargeFilesDetailFmt"] = "{0} dosya · {1}",
        ["Log_Leftovers"] = "Kalıntılar temizlendi",
        ["Log_LeftoversDetailFmt"] = "{0} — {1} öğe · {2}",
        ["Log_MonitorRemoved"] = "Kurulum izleyici: değişiklikler geri alındı",
        ["Log_Privacy"] = "Gizlilik izleri temizlendi",
        ["Log_Restore"] = "Kayıt yedeği geri yüklendi",
        ["Log_Shred"] = "Dosyalar kalıcı olarak yok edildi",
        ["Log_ShredDetailFmt"] = "{0} dosya",
        ["Log_Startup"] = "Başlangıç öğesi değişti",
        ["Log_StoreApp"] = "Windows uygulaması kaldırıldı",
        ["Log_Uninstalled"] = "Kaldırıldı",

        ["Logs_ClearText"] = "Oblivion'un tuttuğu işlem kayıtlarının tamamı silinecek. Yedeklere dokunulmaz.",
        ["Logs_ClearTitle"] = "Kayıtlar temizlensin mi?",
        ["Logs_EmptyText"] = "Kaldırdığınız, temizlediğiniz ve değiştirdiğiniz her şey burada tarihiyle listelenir.",
        ["Logs_EmptyTitle"] = "Kayıt yok",
        ["Logs_OpenFolder"] = "Veri klasörü",
        ["Logs_Search"] = "Kayıtlarda ara",
        ["Logs_Subtitle"] = "Oblivion'un yaptığı her işlemin tarihli kaydı.",

        ["Mon_BaselineDetailFmt"] = "{0} program, {1} klasör",
        ["Mon_BaselineFmt"] = "Son görüntü: {0}",
        ["Mon_BaselineSaved"] = "Görüntü kaydedildi. Şimdi programı kurabilirsiniz.",
        ["Mon_BatteryCyclesFmt"] = "{0} şarj döngüsü",
        ["Mon_BatteryHealthFmt"] = "Sağlık %{0}",
        ["Mon_BatteryRemainingFmt"] = "{0} sa {1} dk kaldı",
        ["Mon_ChangesFmt"] = "{0} değişiklik bulundu",
        ["Mon_Compare"] = "Karşılaştır",
        ["Mon_CoresFmt"] = "{0} çekirdek",
        ["Mon_CriticalFmt"] = "\"{0}\" Windows için gerekli bir işlem; sonlandırılamaz.",
        ["Mon_EmptyText"] = "Bir program kurmadan önce görüntü alın, kurduktan sonra karşılaştırın: kurulumun eklediği her şey burada görünür.",
        ["Mon_EmptyTitle"] = "Kurulumları izleyin",
        ["Mon_EndFailedFmt"] = "\"{0}\" sonlandırılamadı.",
        ["Mon_EndManyTextFmt"] = "Bu adı taşıyan {0} işlemin tamamı kapatılacak. Kaydedilmemiş veriler kaybolabilir.",
        ["Mon_EndText"] = "İşlem kapatılacak. Kaydedilmemiş veriler kaybolabilir.",
        ["Mon_EndTitleFmt"] = "\"{0}\" sonlandırılsın mı?",
        ["Mon_EndedFmt"] = "\"{0}\" sonlandırıldı.",
        ["Mon_KindFolder"] = "Klasör",
        ["Mon_KindProgram"] = "Program",
        ["Mon_KindRegistry"] = "Başlangıç kaydı",
        ["Mon_NoBaseline"] = "Henüz görüntü alınmadı.",
        ["Mon_NoChanges"] = "Değişiklik yok — kurulum hiçbir şey eklememiş.",
        ["Mon_OnAc"] = "Adaptöre bağlı",
        ["Mon_ProgramNotFound"] = "Bu program yüklü programlar listesinde bulunamadı.",
        ["Mon_RamUsedFmt"] = "{0} kullanımda / {1}",
        ["Mon_RemoveSelected"] = "Seçilenleri geri al",
        ["Mon_RemoveText"] = "Klasörler Geri Dönüşüm Kutusu'na taşınır, başlangıç kayıtları yedeklenip silinir. Programlar için \"Kaldır\" düğmesini kullanın.",
        ["Mon_RemoveTitleFmt"] = "{0} değişiklik geri alınsın mı?",
        ["Mon_RemovedDetailFmt"] = "{0} öğe",
        ["Mon_RemovedFmt"] = "{0} değişiklik geri alındı.",
        ["Mon_RetakeText"] = "Mevcut görüntünün yerine yenisi alınacak.",
        ["Mon_RetakeTitle"] = "Yeni görüntü alınsın mı?",
        ["Mon_Step1"] = "1. Görüntü alın",
        ["Mon_Step2"] = "2. Programı kurun",
        ["Mon_Step2Text"] = "Kurulumu her zamanki gibi yapın; Oblivion açık kalabilir.",
        ["Mon_Step3"] = "3. Karşılaştırın",
        ["Mon_Step3Text"] = "Kurulumun eklediği programlar, klasörler ve başlangıç kayıtları listelenir.",
        ["Mon_Subtitle"] = "Bir kurulumun sisteminize tam olarak ne eklediğini görün.",
        ["Mon_TakeBaseline"] = "Görüntü al",
        ["Mon_TempCool"] = "Serin",
        ["Mon_TempHot"] = "Sıcak",
        ["Mon_TempUnavailable"] = "Ölçülemiyor",
        ["Mon_TempWarm"] = "Ilık",
        ["Mon_ThreadsFmt"] = "{0} iş parçacığı",
        ["Mon_UptimeDaysFmt"] = "{0} gün {1} sa {2} dk",
        ["Mon_UptimeFmt"] = "{0} sa {1} dk",

        ["Nav_AllApps"] = "Tüm uygulamalar",
        ["Nav_BrowserExt"] = "Tarayıcı eklentileri",
        ["Nav_Dashboard"] = "Panel",
        ["Nav_Hunter"] = "Avcı modu",
        ["Nav_Logs"] = "Kayıt veritabanı",
        ["Nav_Monitored"] = "Kurulum izleyici",
        ["Nav_Settings"] = "Ayarlar",
        ["Nav_SystemMonitor"] = "Sistem izleyici",
        ["Nav_Tools"] = "Araçlar",
        ["Nav_GroupMain"] = "GENEL",
        ["Nav_GroupMore"] = "TEMİZLİK VE İZLEME",
        ["Nav_WindowsApps"] = "Windows uygulamaları",

        ["Priv_Clean"] = "Temiz",
        ["Priv_CleanSelected"] = "Seçilenleri temizle",
        ["Priv_Clipboard"] = "Pano",
        ["Priv_Clipboard_D"] = "Panoya kopyalanmış metin ve resimler.",
        ["Priv_ConfirmText"] = "Seçilen izler temizlenecek. Dosyalarınıza dokunulmaz; yalnızca kullanım geçmişi silinir.",
        ["Priv_ConfirmTitleFmt"] = "{0} öğe temizlensin mi?",
        ["Priv_Dns"] = "DNS önbelleği",
        ["Priv_Dns_D"] = "Ziyaret edilen sitelerin adres önbelleği.",
        ["Priv_DoneFmt"] = "{0} öğe temizlendi.",
        ["Priv_Footer"] = "Yalnızca kullanım izleri silinir — dosyalarınız güvende.",
        ["Priv_JumpLists"] = "Atlama listeleri",
        ["Priv_JumpLists_D"] = "Görev çubuğundaki son kullanılanlar listeleri.",
        ["Priv_Recent"] = "Son kullanılan belgeler",
        ["Priv_Recent_D"] = "Son açılan dosyaların kısayolları (dosyaların kendisi silinmez).",
        ["Priv_Run"] = "Çalıştır geçmişi",
        ["Priv_Run_D"] = "Win+R penceresine yazdığınız komutlar.",
        ["Priv_Search"] = "Gezgin arama geçmişi",
        ["Priv_Search_D"] = "Dosya Gezgini'nde yaptığınız aramalar.",
        ["Priv_Subtitle"] = "Windows'un tuttuğu kullanım izleri. Hiçbiri otomatik seçilmez.",
        ["Priv_Typed"] = "Adres çubuğu geçmişi",
        ["Priv_Typed_D"] = "Gezgin adres çubuğuna yazılan yollar.",

        ["Quick_Junk"] = "Gereksiz dosyalar",
        ["Quick_Junk_D"] = "Silinecekleri görerek temizleyin",
        ["Quick_LargeFiles"] = "Büyük dosyalar",
        ["Quick_LargeFiles_D"] = "Yer kaplayanları bulun",
        ["Quick_Monitor"] = "Sistem izleyici",
        ["Quick_Monitor_D"] = "CPU, RAM, sıcaklık — canlı",
        ["Quick_Privacy"] = "Gizlilik",
        ["Quick_Privacy_D"] = "Kullanım izlerini silin",
        ["Quick_Startup"] = "Başlangıç",
        ["Quick_Startup_D"] = "Açılışı hızlandırın",
        ["Quick_Uninstall"] = "Program kaldır",
        ["Quick_Uninstall_D"] = "Kalıntılarıyla birlikte",

        ["RP_APPLICATION_INSTALL"] = "Uygulama kurulumu",
        ["RP_APPLICATION_UNINSTALL"] = "Uygulama kaldırma",
        ["RP_CANCELLED_OPERATION"] = "İptal edilen işlem",
        ["RP_DEVICE_DRIVER_INSTALL"] = "Sürücü kurulumu",
        ["RP_MODIFY_SETTINGS"] = "Ayar değişikliği",
        ["RP_SYSTEM"] = "Sistem",

        ["Rail_About"] = "Hakkında",
        ["Rail_Language"] = "Dil: Türkçe / English",
        ["Rail_Theme"] = "Koyu / açık tema",

        ["Reason_AppPath"] = "Programın App Paths kaydı",
        ["Reason_Autostart"] = "Programın başlangıç kaydı",
        ["Reason_Contains"] = "Adında programın adı geçiyor",
        ["Reason_Desktop"] = "Masaüstü kısayolu",
        ["Reason_Exe"] = "Programın .exe adıyla eşleşiyor",
        ["Reason_InstallFolder"] = "Programın kurulum klasörü",
        ["Reason_InstallFolderName"] = "Kurulum klasörüyle aynı ad",
        ["Reason_Name"] = "Program adıyla birebir aynı",
        ["Reason_StartMenu"] = "Başlat menüsü kısayolu",
        ["Reason_UninstallEntry"] = "Geride kalan kaldırma kaydı",
        ["Reason_Vendor"] = "Yayıncının klasörü içinde",

        ["Settings_AboutText"] = "Geliştirici, sürüm ve yenilikler",
        ["Settings_Appearance"] = "Görünüm",
        ["Settings_Confirm"] = "Kaldırmadan önce sor",
        ["Settings_ConfirmText"] = "Her kaldırmada program bilgileriyle bir onay penceresi gösterir.",
        ["Settings_Data"] = "Veri ve hakkında",
        ["Settings_DataFolder"] = "Veri klasörü",
        ["Settings_DataFolderText"] = "Ayarlar, kayıtlar ve yedekler: %LOCALAPPDATA%\\Oblivion",
        ["Settings_Language"] = "Dil",
        ["Settings_LanguageText"] = "Arayüz dili anında değişir.",
        ["Settings_LivePanel"] = "Canlı sistem paneli",
        ["Settings_LivePanelText"] = "Sağdaki CPU, bellek, disk ve ağ göstergeleri (geniş pencerelerde).",
        ["Settings_RecycleBin"] = "Geri Dönüşüm Kutusu'nu kullan",
        ["Settings_RecycleBinText"] = "Kalıntı dosyaları kalıcı silmek yerine Geri Dönüşüm Kutusu'na taşır.",
        ["Settings_ReduceMotion"] = "Animasyonları azalt",
        ["Settings_ReduceMotionText"] = "Giriş animasyonlarını kapatır (eski bilgisayarlar için).",
        ["Settings_RestorePoint"] = "Geri yükleme noktası oluştur",
        ["Settings_RestorePointText"] = "Her kaldırmadan önce bir Windows geri yükleme noktası oluşturur.",
        ["Settings_Silent"] = "Sessiz kaldırma",
        ["Settings_SilentText"] = "Destekleyen programları kaldırıcı penceresi göstermeden kaldırır.",
        ["Settings_Subtitle"] = "Oblivion'u kendinize göre ayarlayın.",
        ["Settings_Theme"] = "Tema",
        ["Settings_ThemeDark"] = "Koyu",
        ["Settings_ThemeLight"] = "Açık",
        ["Settings_ThemeSystem"] = "Sistem",
        ["Settings_ThemeText"] = "Koyu, açık ya da Windows ayarını takip et.",
        ["Settings_Uninstall"] = "Kaldırma",

        ["Shred_AddFiles"] = "Dosya ekle",
        ["Shred_AddFolder"] = "Klasör ekle",
        ["Shred_ConfirmText"] = "Bu öğelerin üzerine yazılıp silinecek. Geri Dönüşüm Kutusu'na GİTMEZ ve hiçbir programla geri getirilemez.",
        ["Shred_ConfirmTitleFmt"] = "{0} öğe kalıcı olarak yok edilsin mi?",
        ["Shred_DoneFmt"] = "{0} dosya kalıcı olarak yok edildi.",
        ["Shred_DonePartialFmt"] = "{0} dosya yok edildi, {1} dosya kullanımda olduğu için atlandı.",
        ["Shred_DropText"] = "Dosyaları buraya sürükleyin ya da yukarıdaki düğmelerle ekleyin.",
        ["Shred_DropTitle"] = "Yok edilecek dosyaları ekleyin",
        ["Shred_Method"] = "Yöntem",
        ["Shred_Pass1"] = "Hızlı (1 geçiş)",
        ["Shred_Pass3"] = "Güçlü (3 geçiş)",
        ["Shred_RefusedFmt"] = "{0} öğe korunan bir sistem konumunda olduğu için eklenmedi.",
        ["Shred_RemoveFromList"] = "Listeden çıkar",
        ["Shred_Subtitle"] = "Dosyaları kurtarılamayacak şekilde silin.",
        ["Shred_TotalFmt"] = "{0} öğe · {1}",
        ["Shred_Warning"] = "Bu araçla silinen dosyalar hiçbir yöntemle geri getirilemez. Windows ve program klasörleri korunur.",

        ["Startup_AllUsersFolder"] = "Tüm kullanıcılar · Başlangıç klasörü",
        ["Startup_AllUsersOnce"] = "Tüm kullanıcılar · bir kez",
        ["Startup_AllUsersRun"] = "Tüm kullanıcılar",
        ["Startup_AllUsersRun32"] = "Tüm kullanıcılar (32 bit)",
        ["Startup_CannotToggle"] = "Bu öğe yalnızca bir kez çalışır; kapatılamaz, sadece silinebilir.",
        ["Startup_DeleteText"] = "Başlangıç kaydı silinecek (önce yedeklenir). Program kaldırılmaz; yalnızca Windows ile birlikte açılmaz. Geçici olarak durdurmak için anahtarı kapatmanız yeterli.",
        ["Startup_DeleteTitleFmt"] = "\"{0}\" başlangıçtan silinsin mi?",
        ["Startup_Deleted"] = "silindi",
        ["Startup_DeletedFmt"] = "\"{0}\" başlangıçtan silindi.",
        ["Startup_DisabledCount"] = "Kapalı",
        ["Startup_DisabledFmt"] = "\"{0}\" artık Windows ile açılmayacak.",
        ["Startup_EnabledCount"] = "Açık",
        ["Startup_EnabledFmt"] = "\"{0}\" Windows ile birlikte açılacak.",
        ["Startup_Off"] = "Kapalı",
        ["Startup_On"] = "Açık",
        ["Startup_Search"] = "Başlangıç öğesi ara",
        ["Startup_Subtitle"] = "Windows ile birlikte açılan programlar. Kapatmak güvenlidir ve her an geri açılabilir.",
        ["Startup_ToggleTip"] = "Windows ile birlikte başlasın mı?",
        ["Startup_Total"] = "Toplam",
        ["Startup_UserFolder"] = "Bu kullanıcı · Başlangıç klasörü",
        ["Startup_UserOnce"] = "Bu kullanıcı · bir kez",
        ["Startup_UserRun"] = "Bu kullanıcı",

        ["Step_RestorePoint"] = "Geri yükleme noktası",
        ["Step_Review"] = "Kalıntıları inceleme",
        ["Step_Scan"] = "Kalıntı taraması",
        ["Step_Uninstaller"] = "Programın kendi kaldırıcısı",

        ["Store_AppsShown"] = "uygulama gösteriliyor",
        ["Store_Loading"] = "Windows uygulamaları okunuyor…",
        ["Store_RemoveFailedFmt"] = "\"{0}\" kaldırılamadı. Bazı yerleşik uygulamaları Windows korur.",
        ["Store_RemoveFrameworkText"] = "Bu bir sistem bileşeni. Başka uygulamalar buna ihtiyaç duyabilir; kaldırmak onları bozabilir.",
        ["Store_RemoveSelected"] = "Seçili uygulamayı kaldır",
        ["Store_RemoveText"] = "Uygulama bu kullanıcı için kaldırılacak. İsterseniz Microsoft Store'dan yeniden yükleyebilirsiniz.",
        ["Store_RemoveTitleFmt"] = "\"{0}\" kaldırılsın mı?",
        ["Store_RemovedFmt"] = "\"{0}\" kaldırıldı.",
        ["Store_Search"] = "Uygulama ara",
        ["Store_ShowSystem"] = "Sistem bileşenlerini göster",
        ["Store_Subtitle"] = "Microsoft Store ve MSIX uygulamaları. Sistem bileşenleri varsayılan olarak gizlidir.",
        ["Store_SystemChip"] = "Sistem",

        ["SysMon_Collecting"] = "Veriler toplanıyor…",
        ["SysMon_Device"] = "Cihaz",
        ["SysMon_Download"] = "indirme",
        ["SysMon_Drives"] = "Sürücüler",
        ["SysMon_Gpu"] = "Ekran kartı",
        ["SysMon_Live"] = "CANLI",
        ["SysMon_Memory"] = "Bellek",
        ["SysMon_Os"] = "Sistem",
        ["SysMon_Process"] = "İşlem",
        ["SysMon_Subtitle"] = "Her saniye güncellenir; sayfa kapalıyken hiç kaynak tüketmez.",
        ["SysMon_TaskManager"] = "Görev Yöneticisi",
        ["SysMon_Temp"] = "Sıcaklık",
        ["SysMon_TempNote"] = "Windows'un bildirdiği en yüksek termal bölge değeri.",
        ["SysMon_ThisPc"] = "Bu bilgisayar",
        ["SysMon_TopProcesses"] = "En çok kaynak kullananlar",
        ["SysMon_Total"] = "Toplam",
        ["SysMon_Upload"] = "yükleme",
        ["SysMon_Uptime"] = "Açık kalma",

        ["Tip_AllGood"] = "Her şey yolunda. Ara sıra gereksiz dosyalara göz atmanız yeterli.",
        ["Tip_CleanJunk"] = "Temizle",
        ["Tip_DiskFullFmt"] = "{0} sürücüsünde yalnızca {1} boş yer kaldı.",
        ["Tip_Hot"] = "İşlemci sıcak çalışıyor. Yoğun programları kontrol edin.",
        ["Tip_ManageStartup"] = "Düzenle",
        ["Tip_MemoryHigh"] = "Bellek kullanımı yüksek.",
        ["Tip_ScanJunk"] = "Tara",
        ["Tip_SeeProcesses"] = "İncele",
        ["Tip_StartupFmt"] = "Windows ile birlikte {0} program açılıyor; açılış yavaşlayabilir.",

        ["Tool_Backups"] = "Yedek yöneticisi",
        ["Tool_Backups_D"] = "Kayıt yedekleri ve geri yükleme noktaları",
        ["Tool_BrowserExt"] = "Tarayıcı eklentileri",
        ["Tool_BrowserExt_D"] = "Tüm tarayıcılardaki eklentileri yönetin",
        ["Tool_Evidence"] = "Kanıt temizleyici",
        ["Tool_Evidence_D"] = "Silinmiş dosyaların izlerini yok edin",
        ["Tool_History"] = "Geçmiş ve gizlilik",
        ["Tool_History_D"] = "Son belgeler, Çalıştır ve arama geçmişi",
        ["Tool_Hunter"] = "Avcı modu",
        ["Tool_Hunter_D"] = "Bir pencereden programını bulun",
        ["Tool_Junk"] = "Gereksiz dosya temizleyici",
        ["Tool_Junk_D"] = "Geçici dosyalar, önbellekler, hata raporları",
        ["Tool_LargeFiles"] = "Büyük dosyalar",
        ["Tool_LargeFiles_D"] = "En çok yer kaplayan dosyalarınız",
        ["Tool_Monitor"] = "Kurulum izleyici",
        ["Tool_Monitor_D"] = "Bir kurulumun eklediği her şeyi görün",
        ["Tool_Shredder"] = "Dosya parçalayıcı",
        ["Tool_Shredder_D"] = "Kurtarılamaz şekilde silin",
        ["Tool_Startup"] = "Başlangıç yöneticisi",
        ["Tool_Startup_D"] = "Windows ile açılan programlar",
        ["Tool_SystemMonitor"] = "Sistem izleyici",
        ["Tool_SystemMonitor_D"] = "CPU, RAM, sıcaklık, ağ — canlı",
        ["Tool_WindowsApps"] = "Windows uygulamaları",
        ["Tool_WindowsApps_D"] = "Store ve yerleşik uygulamalar",

        ["Tools_GroupClean"] = "Temizlik",
        ["Tools_GroupPrivacy"] = "Güvenlik ve gizlilik",
        ["Tools_GroupSystem"] = "Sistem",
        ["Tools_Subtitle"] = "Oblivion'un tüm araçları tek yerde.",

        ["Uninst_ConfirmText"] = "Programın kendi kaldırıcısı çalıştırılacak. Ardından geride kalan dosya ve kayıtlar taranır; neyin silineceğine siz karar verirsiniz.",
        ["Uninst_ConfirmTitleFmt"] = "\"{0}\" kaldırılsın mı?",
        ["Uninst_Declined"] = "Yönetici izni verilmedi.",
        ["Uninst_ExitCodeFmt"] = "Kaldırıcı {0} koduyla bitti.",
        ["Uninst_ForceConfirmText"] = "Kaldırıcı varsa çalıştırılır; bozuk ya da yarım kalmış programlarda bile kalıntılar taranır. Silinecekleri yine siz seçersiniz.",
        ["Uninst_ForceConfirmTitleFmt"] = "\"{0}\" zorla kaldırılsın mı?",
        ["Uninst_NoCommand"] = "Bu program için kaldırma komutu bulunamadı.",
        ["Uninst_NoRestorePoint"] = "Geri yükleme noktası oluşturulmayacak (Ayarlar'dan açabilirsiniz).",
        ["Uninst_NotFinishedText"] = "Program hâlâ yüklü görünüyor; kaldırıcı iptal edilmiş ya da tamamlanmamış olabilir. Şimdi taramak, çalışan programın kendi dosyalarını listeleyebilir.",
        ["Uninst_NotFinishedTitle"] = "Kaldırma tamamlanmadı",
        ["Uninst_ScanAnyway"] = "Yine de tara",
        ["Uninst_StartFailed"] = "Kaldırıcı başlatılamadı.",
        ["Uninst_StoppedFmt"] = "\"{0}\" kaldırılmadı.",
        ["Uninst_WillCreateRestorePoint"] = "Önce bir Windows geri yükleme noktası oluşturulacak.",

        ["Work_Cancelled"] = "İşlem iptal edildi.",
        ["Work_Deleting"] = "Seçilen kalıntılar siliniyor…",
        ["Work_Folders"] = "Program ve veri klasörleri taranıyor…",
        ["Work_InstallFolder"] = "Kurulum klasörü kontrol ediliyor…",
        ["Work_Preparing"] = "Hazırlanıyor…",
        ["Work_Registry"] = "Kayıt defteri taranıyor…",
        ["Work_RestorePoint"] = "Geri yükleme noktası oluşturuluyor…",
        ["Work_RestorePointDescFmt"] = "Oblivion: {0} kaldırılmadan önce",
        ["Work_RestorePointFailed"] = "Geri yükleme noktası oluşturulamadı (Sistem Geri Yükleme kapalı olabilir). Kaldırma devam ediyor.",
        ["Work_RunUninstaller"] = "Programın kaldırıcısı çalışıyor — açılan pencereyi takip edin…",
        ["Work_Shortcuts"] = "Kısayollar taranıyor…",
        ["Work_TitleFmt"] = "{0} kaldırılıyor",
        ["Work_WaitUninstaller"] = "Kaldırıcının bitmesi bekleniyor…",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["About_Copyright"] = "© 2026 ANIL GÜL · All rights reserved.",
        ["About_New1"] = "Redesigned junk cleaner: nothing is pre-selected; open any category to see exactly what will be removed.",
        ["About_New2"] = "New System Monitor: live CPU, memory, temperature, disks, network, battery and top processes.",
        ["About_New3"] = "Safer leftover scan: Microsoft and shared folders are protected, and leftovers are never pre-selected.",
        ["About_New4"] = "New tools: large files, file shredder, history & privacy, evidence remover and a backup manager.",
        ["About_New5"] = "Turn startup programs off and on without deleting them (the same method as Task Manager).",
        ["About_New6"] = "Dark / light / system theme, smoother animations and a much faster start.",
        ["About_New7"] = "Hunter mode crosshair: drag it onto any window to find its program.",
        ["About_Releases"] = "Releases",
        ["About_Repo"] = "View project",
        ["About_Role"] = "Designer & developer of Oblivion",
        ["About_VersionFmt"] = "Version {0}",
        ["About_WhatsNew"] = "What's new",

        ["Act_Cancel"] = "Cancel",
        ["Act_Clean"] = "Clean",
        ["Act_Clear"] = "Clear",
        ["Act_ClearList"] = "Clear list",
        ["Act_Close"] = "Close",
        ["Act_Delete"] = "Delete",
        ["Act_DeleteSelected"] = "Delete selected",
        ["Act_EndTask"] = "End task",
        ["Act_ForceUninstall"] = "Force uninstall",
        ["Act_MoveToRecycle"] = "Move to Recycle Bin",
        ["Act_Open"] = "Open",
        ["Act_OtherCommands"] = "More commands",
        ["Act_Refresh"] = "Refresh",
        ["Act_Remove"] = "Remove",
        ["Act_Restore"] = "Restore",
        ["Act_SelectAll"] = "Select all",
        ["Act_SelectNone"] = "Clear selection",
        ["Act_ShowLocation"] = "Show location",
        ["Act_Shred"] = "Shred permanently",
        ["Act_Stop"] = "Stop",
        ["Act_Uninstall"] = "Uninstall",

        ["App_PerUser"] = "per-user",
        ["App_Tagline"] = "Uninstall · Clean · Monitor",
        ["App_UnknownPublisher"] = "Unknown publisher",

        ["Apps_Architecture"] = "Architecture",
        ["Apps_FilterAll"] = "All",
        ["Apps_FilterLarge"] = "Large",
        ["Apps_FilterRecent"] = "Last 30 days",
        ["Apps_InstallDate"] = "Installed",
        ["Apps_Loading"] = "Reading installed programs…",
        ["Apps_Location"] = "Location",
        ["Apps_Name"] = "Name",
        ["Apps_NoMatch"] = "No matching programs",
        ["Apps_NoMatchText"] = "Try a different search or filter.",
        ["Apps_ProgramsWord"] = "programs",
        ["Apps_Publisher"] = "Publisher",
        ["Apps_RegistryKey"] = "Registry key",
        ["Apps_Search"] = "Search programs or publishers  (Ctrl+F)",
        ["Apps_SelectHint"] = "Select a program from the list",
        ["Apps_Size"] = "Size",
        ["Apps_SortPublisher"] = "Publisher",
        ["Apps_Subtitle"] = "Pick a program and uninstall it, then review and clean what it left behind.",
        ["Apps_UninstallCommand"] = "Uninstall command",
        ["Apps_Version"] = "Version",

        ["Backup_CreatePoint"] = "Create restore point",
        ["Backup_DeleteText"] = "This backup file will be deleted. The registry itself is not changed.",
        ["Backup_DeleteTitle"] = "Delete this backup?",
        ["Backup_ManualPointName"] = "Oblivion — manual restore point",
        ["Backup_NoPointsText"] = "System Restore may be off, or there are no points yet.",
        ["Backup_NoPointsTitle"] = "No restore points",
        ["Backup_NoneText"] = "Whenever Oblivion deletes something from the registry, it saves a backup here first.",
        ["Backup_NoneTitle"] = "No backups yet",
        ["Backup_OpenFolder"] = "Backup folder",
        ["Backup_OpenRestore"] = "System Restore",
        ["Backup_PointCreated"] = "Restore point created.",
        ["Backup_PointFailed"] = "Couldn't create a restore point. System Restore may be turned off.",
        ["Backup_RestoreFailed"] = "The backup could not be restored.",
        ["Backup_RestoreText"] = "This .reg backup will be written back to the registry, bringing the deleted keys and values back.",
        ["Backup_RestoreTitle"] = "Restore this backup?",
        ["Backup_Restored"] = "Backup restored.",
        ["Backup_Subtitle"] = "Registry backups taken before deleting, and Windows restore points.",
        ["Backup_TabRegistry"] = "Registry backups",
        ["Backup_TabRestore"] = "Restore points",

        ["Badge_New"] = "NEW",

        ["Cmd_Copied"] = "Details copied to the clipboard.",
        ["Cmd_CopyDetails"] = "Copy details",
        ["Cmd_CopyFailed"] = "Couldn't copy to the clipboard.",
        ["Cmd_EntryRemoved"] = "Entry removed from the list (a backup was saved).",
        ["Cmd_NoInstallFolder"] = "Install folder not found.",
        ["Cmd_NoWebsite"] = "No publisher website on record.",
        ["Cmd_OpenInstallFolder"] = "Open install folder",
        ["Cmd_OpenRegistry"] = "Open in Registry Editor",
        ["Cmd_OpenWebsite"] = "Publisher website",
        ["Cmd_RemoveEntry"] = "Remove from list (broken entry)",
        ["Cmd_RemoveEntryText"] = "The program's files are not touched; only its uninstall entry is deleted (after a backup). Use it for broken entries whose uninstaller no longer works.",
        ["Cmd_RemoveEntryTitleFmt"] = "Remove \"{0}\" from the list?",
        ["Cmd_SearchWeb"] = "Search the web",

        ["Conf_High"] = "Certain",
        ["Conf_Low"] = "Low",
        ["Conf_Medium"] = "Likely",

        ["Dash_AllLogs"] = "All records",
        ["Dash_Extensions"] = "Browser extensions",
        ["Dash_ExtensionsDetailFmt"] = "in {0} browser(s)",
        ["Dash_GreetDay"] = "Good afternoon",
        ["Dash_GreetEvening"] = "Good evening",
        ["Dash_GreetMorning"] = "Good morning",
        ["Dash_GreetNight"] = "Good night",
        ["Dash_Health"] = "SYSTEM HEALTH",
        ["Dash_NoActivity"] = "Nothing done yet.",
        ["Dash_Programs"] = "Installed programs",
        ["Dash_QuickActions"] = "Quick actions",
        ["Dash_RecentActivity"] = "Recent activity",
        ["Dash_Startup"] = "Start with Windows",
        ["Dash_StartupDetailFmt"] = "{0} on · {1} total",
        ["Dash_StoreApps"] = "Windows apps",
        ["Dash_StoreAppsDetail"] = "Microsoft Store / MSIX",
        ["Dash_Subtitle"] = "Your system at a glance.",
        ["Dash_TotalSizeFmt"] = "{0} in total",

        ["Done_BackToList"] = "Back to the list",
        ["Done_Cleaned"] = "The leftovers you selected were removed.",
        ["Done_FailedFmt"] = "{0} item(s) were in use or protected and were not removed.",
        ["Done_ItemsRemoved"] = "items removed",
        ["Done_NoLeftovers"] = "No leftovers found — all clean.",
        ["Done_Skipped"] = "Leftovers were left in place.",
        ["Done_SpaceFreed"] = "space freed",
        ["Done_TitleFmt"] = "{0} uninstalled",
        ["Done_ToastFmt"] = "{0} leftovers removed · {1} freed",

        ["Evid_ChooseDrive"] = "Choose a drive",
        ["Evid_ConfirmText"] = "All free space on the drive will be overwritten in three passes (0x00, 0xFF, random). Your existing files are not touched. This can take a long time on large drives, and the drive will look full while it runs.",
        ["Evid_ConfirmTitleFmt"] = "Wipe the free space on {0}?",
        ["Evid_Done"] = "Done — deleted files can no longer be recovered.",
        ["Evid_DoneFmt"] = "Free space on {0} wiped.",
        ["Evid_Elapsed"] = "Elapsed",
        ["Evid_Explain"] = "Deleted files leave traces on the disk that recovery tools can bring back. The evidence remover overwrites only FREE space; your existing files stay exactly as they are. It uses Windows' own tool (cipher /w).",
        ["Evid_Failed"] = "Could not wipe the free space.",
        ["Evid_Free"] = "Free",
        ["Evid_Pass1"] = "Pass 1 · zeros",
        ["Evid_Pass2"] = "Pass 2 · ones",
        ["Evid_Pass3"] = "Pass 3 · random",
        ["Evid_PassFmt"] = "Writing pass {0}…",
        ["Evid_Preparing"] = "Preparing…",
        ["Evid_SsdNote"] = "This is an SSD. SSDs already clear deleted data with TRIM, so this is usually unnecessary and adds extra writes.",
        ["Evid_Start"] = "Wipe free space",
        ["Evid_Subtitle"] = "Makes previously deleted files unrecoverable.",

        ["Ext_AllBrowsers"] = "All",
        ["Ext_None"] = "No extensions found",
        ["Ext_NoneText"] = "Edge, Chrome, Brave, Vivaldi, Opera and Firefox were checked.",
        ["Ext_RemoveManyTitleFmt"] = "Remove {0} extensions?",
        ["Ext_RemoveOneTitleFmt"] = "Remove \"{0}\"?",
        ["Ext_RemoveSelected"] = "Remove selected",
        ["Ext_RemoveText"] = "The extension files are moved to the Recycle Bin. If the browser is open, the extension disappears after you restart it.",
        ["Ext_RemovedFmt"] = "{0} extension(s) removed.",
        ["Ext_RunningFmt"] = "Open browsers: {0}. It's best to close them before removing extensions.",
        ["Ext_Search"] = "Search extensions",
        ["Ext_SelectedWord"] = "selected",
        ["Ext_Subtitle"] = "Extensions from every browser in one list. Nothing is pre-selected.",

        ["Health_Attention"] = "Needs some attention",
        ["Health_AttentionText"] = "The suggestions below will help your PC breathe.",
        ["Health_Good"] = "In good shape",
        ["Health_GoodText"] = "A few small improvements are possible.",
        ["Health_Great"] = "Excellent",
        ["Health_GreatText"] = "Your system looks fast and tidy.",

        ["Hunter_BelongsToFmt"] = "This window belongs to \"{0}\".",
        ["Hunter_DragHere"] = "Drag the crosshair onto a window",
        ["Hunter_DragHint"] = "Press, move over the target window and release.",
        ["Hunter_DragTip"] = "Press and drag",
        ["Hunter_EndText"] = "Any unsaved work in the program may be lost.",
        ["Hunter_NotInstalledProgram"] = "Not found among installed programs (it may be portable or part of Windows).",
        ["Hunter_Running"] = "Open windows",
        ["Hunter_Subtitle"] = "Find which program a window belongs to and remove it in one click.",

        ["Junk_Browser"] = "Browser caches",
        ["Junk_Browser_D"] = "Edge, Chrome, Brave, Vivaldi, Opera and Firefox caches. Passwords, bookmarks and history are NOT touched.",
        ["Junk_Browser_Note"] = "Files in use are skipped while a browser is open; pages may load a little slower the first time.",
        ["Junk_CleanSelected"] = "Clean selected",
        ["Junk_Cleaning"] = "Cleaning…",
        ["Junk_ConfirmBinNote"] = "The Recycle Bin will be emptied — this can't be undone.",
        ["Junk_ConfirmDeleteNote"] = "Temporary files and caches are deleted permanently; files in use are skipped.",
        ["Junk_ConfirmRecycleNote"] = "Downloaded installers go to the Recycle Bin, so they can be restored.",
        ["Junk_ConfirmTitleFmt"] = "Clean {0}?",
        ["Junk_Crash"] = "Crash reports and dumps",
        ["Junk_Crash_D"] = "Windows error reports, app crash dumps and MEMORY.DMP.",
        ["Junk_ExpandAll"] = "Expand / collapse all",
        ["Junk_ExpandAllTip"] = "Show the contents of every category",
        ["Junk_Found"] = "Found",
        ["Junk_Freed"] = "freed",
        ["Junk_GroupDetail"] = "Many small files combined",
        ["Junk_GroupFmt"] = "… and {0} more",
        ["Junk_Installers"] = "Downloaded installers",
        ["Junk_Installers_D"] = "Setup files (.exe, .msi, .msix) in your Downloads folder.",
        ["Junk_Installers_Note"] = "These are your own files: they go to the Recycle Bin instead of being deleted.",
        ["Junk_ItemsFmt"] = "{0} items",
        ["Junk_Nothing"] = "Clean",
        ["Junk_NothingSelected"] = "Nothing selected",
        ["Junk_RecycleBin"] = "Recycle Bin",
        ["Junk_RecycleBin_D"] = "Files you deleted earlier.",
        ["Junk_RecycleBin_Note"] = "Emptying it can't be undone.",
        ["Junk_Rescan"] = "Scan again",
        ["Junk_ResultFmt"] = "{0} items removed.",
        ["Junk_ResultSkippedFmt"] = "{0} items removed, {1} in use were skipped.",
        ["Junk_Scanning"] = "Scanning…",
        ["Junk_SelectCategoryTip"] = "Select or clear everything in this category",
        ["Junk_Selected"] = "Selected",
        ["Junk_SelectedFmt"] = "Selected: {0}",
        ["Junk_SelectedTotalFmt"] = "{0} items · {1}",
        ["Junk_ShowItems"] = "Show what would be removed",
        ["Junk_Subtitle"] = "Nothing is selected for you. Open a category, see exactly what would be removed and tick it yourself.",
        ["Junk_Thumbs"] = "Thumbnail and icon cache",
        ["Junk_Thumbs_D"] = "File Explorer's thumbnail (thumbcache) and icon cache files.",
        ["Junk_Thumbs_Note"] = "Windows rebuilds these when needed; some may be skipped while Explorer is running.",
        ["Junk_ToastFmt"] = "{0} freed",
        ["Junk_Update"] = "Windows Update downloads",
        ["Junk_Update_D"] = "Download files of installed updates (SoftwareDistribution\\Download).",
        ["Junk_Update_Note"] = "If an update is still pending, Windows simply downloads the files again.",
        ["Junk_UserTemp"] = "User temporary files",
        ["Junk_UserTemp_D"] = "Temporary files programs leave in your %TEMP% folder.",
        ["Junk_WinTemp"] = "Windows temporary files",
        ["Junk_WinTemp_D"] = "Temporary files in the Windows\\Temp folder.",

        ["Large_Drive"] = "Local Disk",
        ["Large_EmptyText"] = "Pick a location and a minimum size, then press Scan. Windows, program and AppData folders are never scanned.",
        ["Large_EmptyTitle"] = "Find what's taking up space",
        ["Large_FoundFmt"] = "{0} files found · {1} in total",
        ["Large_MinSize"] = "Minimum size",
        ["Large_NoneFmt"] = "No files larger than {0}.",
        ["Large_PickFolder"] = "Choose a folder",
        ["Large_RecycleText"] = "The files are moved to the Recycle Bin, so you can restore them if needed.",
        ["Large_RecycleTitleFmt"] = "Move {0} files ({1}) to the Recycle Bin?",
        ["Large_RecycledFmt"] = "{0} files moved · {1} freed",
        ["Large_Scan"] = "Scan",
        ["Large_ScannedFmt"] = "{0} files checked…",
        ["Large_SelectedFmt"] = "{0} files selected · {1}",
        ["Large_Starting"] = "Starting…",
        ["Large_Subtitle"] = "The personal files taking up the most space. Nothing is pre-selected.",
        ["Large_UserFolder"] = "My user folder",
        ["Large_Where"] = "Where to look",

        ["Left_All"] = "All",
        ["Left_DeleteTextPermanent"] = "Files are deleted permanently. Registry items are backed up first (restorable from the backup manager).",
        ["Left_DeleteTextRecycle"] = "Files and folders go to the Recycle Bin. Registry items are backed up first (restorable from the backup manager).",
        ["Left_DeleteTitleFmt"] = "Delete {0} leftovers?",
        ["Left_Explain"] = "No leftover is pre-selected. Each row shows why it was found and how sure we are: \"Certain\" items are the program's own folders and keys; check \"Low\" ones carefully. Windows and Microsoft locations are never listed.",
        ["Left_Files"] = "Files",
        ["Left_Finish"] = "Finish without deleting",
        ["Left_FoundFor"] = "Leftovers of",
        ["Left_LowWarningFmt"] = "Careful: {0} item(s) are low-confidence matches. Only delete them if you're sure.",
        ["Left_NoneSelected"] = "Nothing selected to delete",
        ["Left_Registry"] = "Registry",
        ["Left_SelectSafe"] = "Select certain ones",
        ["Left_SelectSafeTip"] = "Selects only the certain matches",
        ["Left_SelectedFmt"] = "{0} selected · {1}",
        ["Left_StillInstalled"] = "The program still appears to be installed. These items may belong to the working program — check carefully before deleting.",
        ["Left_SummaryFmt"] = "{0} items found · {1}",

        ["Live_BatteryChargingFmt"] = "Battery {0}% · charging",
        ["Live_BatteryFmt"] = "Battery {0}%",
        ["Live_Cpu"] = "CPU",
        ["Live_Details"] = "Details",
        ["Live_Disk"] = "Disk",
        ["Live_DiskFreeFmt"] = "{0} free of {1}",
        ["Live_Network"] = "Network",
        ["Live_Ram"] = "Memory",
        ["Live_TempNA"] = "no sensor",
        ["Live_Title"] = "Live system",

        ["Log_Backup"] = "Restore point created",
        ["Log_Baseline"] = "Install monitor: snapshot taken",
        ["Log_EndTask"] = "Task ended",
        ["Log_EntryRemoved"] = "Broken entry removed",
        ["Log_Evidence"] = "Free space wiped",
        ["Log_Extension"] = "Browser extension removed",
        ["Log_Forced"] = "Force uninstalled",
        ["Log_History"] = "History cleared",
        ["Log_Junk"] = "Junk cleaned",
        ["Log_JunkDetailFmt"] = "{0} freed · {1} items",
        ["Log_LargeFiles"] = "Large files moved",
        ["Log_LargeFilesDetailFmt"] = "{0} files · {1}",
        ["Log_Leftovers"] = "Leftovers removed",
        ["Log_LeftoversDetailFmt"] = "{0} — {1} items · {2}",
        ["Log_MonitorRemoved"] = "Install monitor: changes undone",
        ["Log_Privacy"] = "Privacy traces cleared",
        ["Log_Restore"] = "Registry backup restored",
        ["Log_Shred"] = "Files shredded",
        ["Log_ShredDetailFmt"] = "{0} files",
        ["Log_Startup"] = "Startup item changed",
        ["Log_StoreApp"] = "Windows app removed",
        ["Log_Uninstalled"] = "Uninstalled",

        ["Logs_ClearText"] = "All of Oblivion's activity records will be deleted. Backups are not touched.",
        ["Logs_ClearTitle"] = "Clear the log?",
        ["Logs_EmptyText"] = "Everything you uninstall, clean or change is listed here with its date.",
        ["Logs_EmptyTitle"] = "No records",
        ["Logs_OpenFolder"] = "Data folder",
        ["Logs_Search"] = "Search the log",
        ["Logs_Subtitle"] = "A dated record of everything Oblivion did.",

        ["Mon_BaselineDetailFmt"] = "{0} programs, {1} folders",
        ["Mon_BaselineFmt"] = "Last snapshot: {0}",
        ["Mon_BaselineSaved"] = "Snapshot saved. You can install the program now.",
        ["Mon_BatteryCyclesFmt"] = "{0} charge cycles",
        ["Mon_BatteryHealthFmt"] = "Health {0}%",
        ["Mon_BatteryRemainingFmt"] = "{0} h {1} min left",
        ["Mon_ChangesFmt"] = "{0} changes found",
        ["Mon_Compare"] = "Compare",
        ["Mon_CoresFmt"] = "{0} cores",
        ["Mon_CriticalFmt"] = "\"{0}\" is needed by Windows and can't be ended.",
        ["Mon_EmptyText"] = "Take a snapshot before installing a program and compare afterwards: everything the installer added shows up here.",
        ["Mon_EmptyTitle"] = "Watch installations",
        ["Mon_EndFailedFmt"] = "Couldn't end \"{0}\".",
        ["Mon_EndManyTextFmt"] = "All {0} processes with this name will be closed. Unsaved work may be lost.",
        ["Mon_EndText"] = "The process will be closed. Unsaved work may be lost.",
        ["Mon_EndTitleFmt"] = "End \"{0}\"?",
        ["Mon_EndedFmt"] = "\"{0}\" ended.",
        ["Mon_KindFolder"] = "Folder",
        ["Mon_KindProgram"] = "Program",
        ["Mon_KindRegistry"] = "Startup entry",
        ["Mon_NoBaseline"] = "No snapshot yet.",
        ["Mon_NoChanges"] = "No changes — the installer added nothing.",
        ["Mon_OnAc"] = "Plugged in",
        ["Mon_ProgramNotFound"] = "This program wasn't found in the installed programs list.",
        ["Mon_RamUsedFmt"] = "{0} in use of {1}",
        ["Mon_RemoveSelected"] = "Undo selected",
        ["Mon_RemoveText"] = "Folders go to the Recycle Bin; startup entries are backed up and deleted. Use \"Uninstall\" for programs.",
        ["Mon_RemoveTitleFmt"] = "Undo {0} changes?",
        ["Mon_RemovedDetailFmt"] = "{0} items",
        ["Mon_RemovedFmt"] = "{0} changes undone.",
        ["Mon_RetakeText"] = "The current snapshot will be replaced with a new one.",
        ["Mon_RetakeTitle"] = "Take a new snapshot?",
        ["Mon_Step1"] = "1. Take a snapshot",
        ["Mon_Step2"] = "2. Install the program",
        ["Mon_Step2Text"] = "Install it as usual; Oblivion can stay open.",
        ["Mon_Step3"] = "3. Compare",
        ["Mon_Step3Text"] = "Programs, folders and startup entries the installer added are listed.",
        ["Mon_Subtitle"] = "See exactly what an installer adds to your system.",
        ["Mon_TakeBaseline"] = "Take snapshot",
        ["Mon_TempCool"] = "Cool",
        ["Mon_TempHot"] = "Hot",
        ["Mon_TempUnavailable"] = "Not available",
        ["Mon_TempWarm"] = "Warm",
        ["Mon_ThreadsFmt"] = "{0} threads",
        ["Mon_UptimeDaysFmt"] = "{0} d {1} h {2} min",
        ["Mon_UptimeFmt"] = "{0} h {1} min",

        ["Nav_AllApps"] = "All applications",
        ["Nav_BrowserExt"] = "Browser extensions",
        ["Nav_Dashboard"] = "Dashboard",
        ["Nav_Hunter"] = "Hunter mode",
        ["Nav_Logs"] = "Logs database",
        ["Nav_Monitored"] = "Install monitor",
        ["Nav_Settings"] = "Settings",
        ["Nav_SystemMonitor"] = "System monitor",
        ["Nav_Tools"] = "Tools",
        ["Nav_GroupMain"] = "GENERAL",
        ["Nav_GroupMore"] = "CLEANING & TRACKING",
        ["Nav_WindowsApps"] = "Windows apps",

        ["Priv_Clean"] = "Clean",
        ["Priv_CleanSelected"] = "Clean selected",
        ["Priv_Clipboard"] = "Clipboard",
        ["Priv_Clipboard_D"] = "Text and images on the clipboard.",
        ["Priv_ConfirmText"] = "The selected traces will be cleared. Your files are not touched; only usage history is removed.",
        ["Priv_ConfirmTitleFmt"] = "Clear {0} items?",
        ["Priv_Dns"] = "DNS cache",
        ["Priv_Dns_D"] = "Cached addresses of visited sites.",
        ["Priv_DoneFmt"] = "{0} items cleared.",
        ["Priv_Footer"] = "Only usage traces are removed — your files are safe.",
        ["Priv_JumpLists"] = "Jump lists",
        ["Priv_JumpLists_D"] = "Recent-item lists on the taskbar.",
        ["Priv_Recent"] = "Recent documents",
        ["Priv_Recent_D"] = "Shortcuts to recently opened files (not the files themselves).",
        ["Priv_Run"] = "Run history",
        ["Priv_Run_D"] = "Commands typed into the Win+R box.",
        ["Priv_Search"] = "Explorer search history",
        ["Priv_Search_D"] = "Searches made in File Explorer.",
        ["Priv_Subtitle"] = "Usage traces Windows keeps. Nothing is pre-selected.",
        ["Priv_Typed"] = "Address bar history",
        ["Priv_Typed_D"] = "Paths typed into Explorer's address bar.",

        ["Quick_Junk"] = "Junk files",
        ["Quick_Junk_D"] = "Clean while seeing every file",
        ["Quick_LargeFiles"] = "Large files",
        ["Quick_LargeFiles_D"] = "Find space hogs",
        ["Quick_Monitor"] = "System monitor",
        ["Quick_Monitor_D"] = "CPU, RAM, temperature — live",
        ["Quick_Privacy"] = "Privacy",
        ["Quick_Privacy_D"] = "Clear usage traces",
        ["Quick_Startup"] = "Startup",
        ["Quick_Startup_D"] = "Speed up boot",
        ["Quick_Uninstall"] = "Uninstall a program",
        ["Quick_Uninstall_D"] = "Together with its leftovers",

        ["RP_APPLICATION_INSTALL"] = "Application install",
        ["RP_APPLICATION_UNINSTALL"] = "Application uninstall",
        ["RP_CANCELLED_OPERATION"] = "Cancelled operation",
        ["RP_DEVICE_DRIVER_INSTALL"] = "Driver install",
        ["RP_MODIFY_SETTINGS"] = "Settings change",
        ["RP_SYSTEM"] = "System",

        ["Rail_About"] = "About",
        ["Rail_Language"] = "Language: Türkçe / English",
        ["Rail_Theme"] = "Dark / light theme",

        ["Reason_AppPath"] = "The program's App Paths entry",
        ["Reason_Autostart"] = "The program's startup entry",
        ["Reason_Contains"] = "Its name contains the program's name",
        ["Reason_Desktop"] = "Desktop shortcut",
        ["Reason_Exe"] = "Matches the program's .exe name",
        ["Reason_InstallFolder"] = "The program's install folder",
        ["Reason_InstallFolderName"] = "Same name as the install folder",
        ["Reason_Name"] = "Exactly the program's name",
        ["Reason_StartMenu"] = "Start menu shortcut",
        ["Reason_UninstallEntry"] = "Orphaned uninstall entry",
        ["Reason_Vendor"] = "Inside the publisher's folder",

        ["Settings_AboutText"] = "Developer, version and what's new",
        ["Settings_Appearance"] = "Appearance",
        ["Settings_Confirm"] = "Ask before uninstalling",
        ["Settings_ConfirmText"] = "Shows a confirmation with the program's details every time.",
        ["Settings_Data"] = "Data & about",
        ["Settings_DataFolder"] = "Data folder",
        ["Settings_DataFolderText"] = "Settings, log and backups: %LOCALAPPDATA%\\Oblivion",
        ["Settings_Language"] = "Language",
        ["Settings_LanguageText"] = "The interface switches immediately.",
        ["Settings_LivePanel"] = "Live system panel",
        ["Settings_LivePanelText"] = "CPU, memory, disk and network meters on the right (on wide windows).",
        ["Settings_RecycleBin"] = "Use the Recycle Bin",
        ["Settings_RecycleBinText"] = "Moves leftover files to the Recycle Bin instead of deleting them.",
        ["Settings_ReduceMotion"] = "Reduce animations",
        ["Settings_ReduceMotionText"] = "Turns off entrance animations (for older PCs).",
        ["Settings_RestorePoint"] = "Create a restore point",
        ["Settings_RestorePointText"] = "Creates a Windows restore point before every uninstall.",
        ["Settings_Silent"] = "Silent uninstall",
        ["Settings_SilentText"] = "Removes programs that support it without showing their uninstaller.",
        ["Settings_Subtitle"] = "Make Oblivion yours.",
        ["Settings_Theme"] = "Theme",
        ["Settings_ThemeDark"] = "Dark",
        ["Settings_ThemeLight"] = "Light",
        ["Settings_ThemeSystem"] = "System",
        ["Settings_ThemeText"] = "Dark, light, or follow Windows.",
        ["Settings_Uninstall"] = "Uninstalling",

        ["Shred_AddFiles"] = "Add files",
        ["Shred_AddFolder"] = "Add folder",
        ["Shred_ConfirmText"] = "These items will be overwritten and deleted. They do NOT go to the Recycle Bin and can't be recovered by any tool.",
        ["Shred_ConfirmTitleFmt"] = "Permanently shred {0} items?",
        ["Shred_DoneFmt"] = "{0} files shredded.",
        ["Shred_DonePartialFmt"] = "{0} files shredded, {1} were in use and skipped.",
        ["Shred_DropText"] = "Drag files here or add them with the buttons above.",
        ["Shred_DropTitle"] = "Add files to shred",
        ["Shred_Method"] = "Method",
        ["Shred_Pass1"] = "Quick (1 pass)",
        ["Shred_Pass3"] = "Strong (3 passes)",
        ["Shred_RefusedFmt"] = "{0} item(s) are in protected system locations and were not added.",
        ["Shred_RemoveFromList"] = "Remove from list",
        ["Shred_Subtitle"] = "Delete files so they can never be recovered.",
        ["Shred_TotalFmt"] = "{0} items · {1}",
        ["Shred_Warning"] = "Files shredded here can't be brought back by any means. Windows and program folders are protected.",

        ["Startup_AllUsersFolder"] = "All users · Startup folder",
        ["Startup_AllUsersOnce"] = "All users · run once",
        ["Startup_AllUsersRun"] = "All users",
        ["Startup_AllUsersRun32"] = "All users (32-bit)",
        ["Startup_CannotToggle"] = "This item runs only once; it can't be switched off, only deleted.",
        ["Startup_DeleteText"] = "The startup entry will be deleted (after a backup). The program is not uninstalled, it just won't start with Windows. To stop it temporarily, simply switch it off.",
        ["Startup_DeleteTitleFmt"] = "Delete \"{0}\" from startup?",
        ["Startup_Deleted"] = "deleted",
        ["Startup_DeletedFmt"] = "\"{0}\" removed from startup.",
        ["Startup_DisabledCount"] = "Off",
        ["Startup_DisabledFmt"] = "\"{0}\" won't start with Windows anymore.",
        ["Startup_EnabledCount"] = "On",
        ["Startup_EnabledFmt"] = "\"{0}\" will start with Windows.",
        ["Startup_Off"] = "Off",
        ["Startup_On"] = "On",
        ["Startup_Search"] = "Search startup items",
        ["Startup_Subtitle"] = "Programs that start with Windows. Switching one off is safe and can be undone any time.",
        ["Startup_ToggleTip"] = "Start with Windows?",
        ["Startup_Total"] = "Total",
        ["Startup_UserFolder"] = "This user · Startup folder",
        ["Startup_UserOnce"] = "This user · run once",
        ["Startup_UserRun"] = "This user",

        ["Step_RestorePoint"] = "Restore point",
        ["Step_Review"] = "Review leftovers",
        ["Step_Scan"] = "Leftover scan",
        ["Step_Uninstaller"] = "The program's own uninstaller",

        ["Store_AppsShown"] = "apps shown",
        ["Store_Loading"] = "Reading Windows apps…",
        ["Store_RemoveFailedFmt"] = "Couldn't remove \"{0}\". Windows protects some built-in apps.",
        ["Store_RemoveFrameworkText"] = "This is a system component. Other apps may depend on it; removing it can break them.",
        ["Store_RemoveSelected"] = "Remove selected app",
        ["Store_RemoveText"] = "The app will be removed for this user. You can reinstall it from the Microsoft Store.",
        ["Store_RemoveTitleFmt"] = "Remove \"{0}\"?",
        ["Store_RemovedFmt"] = "\"{0}\" removed.",
        ["Store_Search"] = "Search apps",
        ["Store_ShowSystem"] = "Show system components",
        ["Store_Subtitle"] = "Microsoft Store and MSIX apps. System components are hidden by default.",
        ["Store_SystemChip"] = "System",

        ["SysMon_Collecting"] = "Collecting data…",
        ["SysMon_Device"] = "Device",
        ["SysMon_Download"] = "download",
        ["SysMon_Drives"] = "Drives",
        ["SysMon_Gpu"] = "Graphics",
        ["SysMon_Live"] = "LIVE",
        ["SysMon_Memory"] = "Memory",
        ["SysMon_Os"] = "System",
        ["SysMon_Process"] = "Process",
        ["SysMon_Subtitle"] = "Updates every second; uses no resources while closed.",
        ["SysMon_TaskManager"] = "Task Manager",
        ["SysMon_Temp"] = "Temperature",
        ["SysMon_TempNote"] = "Highest thermal-zone reading reported by Windows.",
        ["SysMon_ThisPc"] = "This PC",
        ["SysMon_TopProcesses"] = "Top processes",
        ["SysMon_Total"] = "Total",
        ["SysMon_Upload"] = "upload",
        ["SysMon_Uptime"] = "Uptime",

        ["Tip_AllGood"] = "All good. An occasional look at junk files is all it needs.",
        ["Tip_CleanJunk"] = "Clean up",
        ["Tip_DiskFullFmt"] = "Only {1} free on drive {0}.",
        ["Tip_Hot"] = "The CPU is running hot. Check heavy programs.",
        ["Tip_ManageStartup"] = "Manage",
        ["Tip_MemoryHigh"] = "Memory usage is high.",
        ["Tip_ScanJunk"] = "Scan",
        ["Tip_SeeProcesses"] = "Inspect",
        ["Tip_StartupFmt"] = "{0} programs start with Windows, which can slow down boot.",

        ["Tool_Backups"] = "Backup manager",
        ["Tool_Backups_D"] = "Registry backups and restore points",
        ["Tool_BrowserExt"] = "Browser extensions",
        ["Tool_BrowserExt_D"] = "Manage extensions in every browser",
        ["Tool_Evidence"] = "Evidence remover",
        ["Tool_Evidence_D"] = "Erase traces of deleted files",
        ["Tool_History"] = "History & privacy",
        ["Tool_History_D"] = "Recent documents, Run and search history",
        ["Tool_Hunter"] = "Hunter mode",
        ["Tool_Hunter_D"] = "Find a program from its window",
        ["Tool_Junk"] = "Junk cleaner",
        ["Tool_Junk_D"] = "Temp files, caches, crash reports",
        ["Tool_LargeFiles"] = "Large files",
        ["Tool_LargeFiles_D"] = "Your biggest files",
        ["Tool_Monitor"] = "Install monitor",
        ["Tool_Monitor_D"] = "See everything an installer adds",
        ["Tool_Shredder"] = "File shredder",
        ["Tool_Shredder_D"] = "Delete beyond recovery",
        ["Tool_Startup"] = "Startup manager",
        ["Tool_Startup_D"] = "Programs that start with Windows",
        ["Tool_SystemMonitor"] = "System monitor",
        ["Tool_SystemMonitor_D"] = "CPU, RAM, temperature, network — live",
        ["Tool_WindowsApps"] = "Windows apps",
        ["Tool_WindowsApps_D"] = "Store and built-in apps",

        ["Tools_GroupClean"] = "Cleaning",
        ["Tools_GroupPrivacy"] = "Security & privacy",
        ["Tools_GroupSystem"] = "System",
        ["Tools_Subtitle"] = "All of Oblivion's tools in one place.",

        ["Uninst_ConfirmText"] = "The program's own uninstaller will run. Then leftover files and registry entries are scanned, and you decide what gets deleted.",
        ["Uninst_ConfirmTitleFmt"] = "Uninstall \"{0}\"?",
        ["Uninst_Declined"] = "Administrator permission was declined.",
        ["Uninst_ExitCodeFmt"] = "The uninstaller exited with code {0}.",
        ["Uninst_ForceConfirmText"] = "The uninstaller runs if there is one; leftovers are scanned even for broken or half-removed programs. You still choose what gets deleted.",
        ["Uninst_ForceConfirmTitleFmt"] = "Force uninstall \"{0}\"?",
        ["Uninst_NoCommand"] = "No uninstall command was found for this program.",
        ["Uninst_NoRestorePoint"] = "No restore point will be created (you can turn it on in Settings).",
        ["Uninst_NotFinishedText"] = "The program still appears to be installed; the uninstaller may have been cancelled or not finished. Scanning now could list the working program's own files.",
        ["Uninst_NotFinishedTitle"] = "Uninstall not finished",
        ["Uninst_ScanAnyway"] = "Scan anyway",
        ["Uninst_StartFailed"] = "The uninstaller could not be started.",
        ["Uninst_StoppedFmt"] = "\"{0}\" was not uninstalled.",
        ["Uninst_WillCreateRestorePoint"] = "A Windows restore point will be created first.",

        ["Work_Cancelled"] = "Cancelled.",
        ["Work_Deleting"] = "Removing the selected leftovers…",
        ["Work_Folders"] = "Scanning program and data folders…",
        ["Work_InstallFolder"] = "Checking the install folder…",
        ["Work_Preparing"] = "Preparing…",
        ["Work_Registry"] = "Scanning the registry…",
        ["Work_RestorePoint"] = "Creating a restore point…",
        ["Work_RestorePointDescFmt"] = "Oblivion: before uninstalling {0}",
        ["Work_RestorePointFailed"] = "Couldn't create a restore point (System Restore may be off). Continuing.",
        ["Work_RunUninstaller"] = "The program's uninstaller is running — follow its window…",
        ["Work_Shortcuts"] = "Scanning shortcuts…",
        ["Work_TitleFmt"] = "Uninstalling {0}",
        ["Work_WaitUninstaller"] = "Waiting for the uninstaller to finish…",
    };
}
