import Foundation
import SwiftUI

/// Live Turkish / English localization (same model as the Windows version).
final class Loc: ObservableObject {
    @Published var lang: String = "tr" {
        didSet { UserDefaults.standard.set(lang, forKey: "oblivion.lang") }
    }

    init() {
        if let saved = UserDefaults.standard.string(forKey: "oblivion.lang") {
            lang = saved
        } else {
            lang = (Locale.preferredLanguages.first ?? "tr").hasPrefix("tr") ? "tr" : "en"
        }
    }

    var isTurkish: Bool { lang == "tr" }

    func toggle() { lang = isTurkish ? "en" : "tr" }

    subscript(_ key: String) -> String {
        (isTurkish ? Loc.tr[key] : Loc.en[key]) ?? Loc.en[key] ?? key
    }

    /// Lookup with `{placeholder}` substitution.
    func t(_ key: String, _ args: [String: String]) -> String {
        var text = self[key]
        for (name, value) in args {
            text = text.replacingOccurrences(of: "{\(name)}", with: value)
        }
        return text
    }

    // MARK: English

    static let en: [String: String] = [

        "nav.dashboard": "Dashboard",
        "nav.apps": "All applications",
        "nav.store": "App Store apps",
        "nav.monitor": "Monitored installs",
        "nav.browser": "Browser extensions",
        "nav.logs": "Logs database",
        "nav.hunter": "Hunter mode",
        "nav.tools": "Tools",
        "nav.settings": "Settings",

        "rail.theme": "Theme (dark / light / system)",
        "rail.language": "Language (TR / EN)",

        "action.uninstall": "Uninstall",
        "action.force": "Force uninstall",
        "action.more": "Other commands",
        "action.hint": "Select an app from the list",
        "action.refresh": "Refresh",
        "action.cancel": "Cancel",
        "action.ok": "OK",
        "action.open": "Open",
        "action.remove": "Remove",
        "action.selectAll": "Select all",
        "action.selectNone": "None",
        "action.skip": "Skip",

        "cmd.open": "Open app",
        "cmd.reveal": "Show in Finder",
        "cmd.contents": "Show package contents",
        "cmd.info": "Get info",
        "cmd.copy": "Copy details",
        "cmd.web": "Search the web",

        "col.app": "Application",
        "col.size": "Size",
        "col.version": "Version",
        "col.arch": "Architecture",
        "col.installed": "Installed",
        "col.lastUsed": "Last opened",
        "col.source": "Source",
        "arch.universal": "Universal",

        "apps.subtitle": "{count} apps · {size}",
        "apps.search": "Search apps or bundle IDs…",
        "apps.loading": "Reading installed applications…",
        "apps.empty": "No applications match your search.",
        "apps.emptyStore": "No Mac App Store apps found.",
        "desc.empty": "Select an application to see its details here.",

        "confirm.title": "Uninstall this app?",
        "confirm.message": "“{name}” will be moved to the Trash, then Oblivion will scan for leftovers so you can review them.",
        "error.title": "Something went wrong",
        "error.removeFailed": "The app couldn't be moved to the Trash. If macOS asked for permission, please allow it and try again.",

        "work.quitting": "Closing the app and moving it to the Trash…",
        "work.scanning": "Scanning Library folders for leftovers…",
        "work.removing": "Removing selected leftovers…",

        "left.title": "Leftovers found",
        "left.subtitle": "{name} · {count} items",
        "left.info": "Review what was left behind. Nothing is selected for you — tick what should go, or use “Select exact matches” for the items named after the app's bundle ID. Everything goes to the Trash, so it can be restored. 🔒 items need your password.",
        "left.selected": "{count} selected · {size}",
        "left.remove": "Delete selected",
        "left.receipt": "Installer receipt (pkgutil)",
        "left.admin": "Requires administrator password",
        "conf.high": "Exact",
        "conf.medium": "Likely",
        "conf.low": "Possible",

        "done.title": "All clean!",
        "done.freed": "Space freed",
        "done.items": "Items removed",
        "done.back": "Back to the list",

        "force.title": "Force uninstall",
        "force.subtitle": "Deep-scan for an app's traces — even if it's already deleted or broken.",
        "force.placeholder": "App name or bundle ID (e.g. Spotify or com.spotify.client)",
        "force.hint": "Tip: drag an app onto this window to fill it in automatically.",
        "force.scan": "Scan & remove",

        "dash.subtitle": "Your Mac at a glance",
        "dash.apps": "Installed apps",
        "dash.footprint": "Total app size",
        "dash.measuring": "Measuring sizes…",
        "dash.launchItems": "Startup items",
        "dash.freeSpace": "Free disk space",
        "dash.quick": "Quick actions",
        "dash.largest": "Largest applications",
        "dash.activity": "Recent activity",
        "dash.allLogs": "All logs",
        "dash.noActivity": "Your uninstall and cleanup history will appear here.",

        "fda.title": "Give Oblivion Full Disk Access",
        "fda.body": "Without it, some leftovers (containers, Mail, Safari data…) stay hidden from the scan.",
        "fda.open": "Open settings",

        "right.system": "System",
        "right.chip": "Chip",
        "right.memory": "Memory",
        "right.activity": "Recent activity",

        "mon.subtitle": "Trace an installation, then remove everything it added.",
        "mon.step1": "Take a baseline snapshot of your Mac",
        "mon.step2": "Install (or run) the program you want to trace",
        "mon.step3": "Compare — Oblivion lists everything that was added",
        "mon.baseline": "Take baseline",
        "mon.compare": "Compare",
        "mon.baselineAt": "Baseline: {date}",
        "mon.ready": "Baseline ready. Install something, then press Compare.",
        "mon.noBaseline": "Start by taking a baseline snapshot.",
        "mon.noChanges": "Nothing new was added since the baseline.",
        "mon.found": "{count} new items since the baseline",
        "mon.remove": "Remove selected",
        "mon.kind.app": "App",
        "mon.kind.folder": "Folder",
        "mon.kind.preferences": "Preferences",
        "mon.kind.launchItem": "Launch item",
        "mon.kind.receipt": "Receipt",

        "br.subtitle": "Chrome, Edge, Brave, Arc, Vivaldi, Opera, Firefox and Safari",
        "br.note": "Quit the browser before removing an extension. Synced extensions may come back from your browser account.",
        "br.loading": "Looking for browser extensions…",
        "br.empty": "No browser extensions found.",
        "br.managedBySafari": "Remove its app",

        "logs.subtitle": "Everything Oblivion has done on this Mac",
        "logs.clear": "Clear log",
        "logs.clearConfirm": "Clear the whole activity log?",

        "log.uninstalled": "Uninstalled",
        "log.forced": "Force uninstall",
        "log.leftovers": "Leftovers removed",
        "log.junk": "Junk cleaned",
        "log.extension": "Extension removed",
        "log.shred": "Files shredded",
        "log.history": "History cleared",
        "log.baseline": "Baseline taken",
        "log.monitorRemoved": "Traced items removed",
        "log.launchItem": "Startup item removed",
        "log.largeFiles": "Large files trashed",

        "hunt.subtitle": "Aim at any running app — quit it, find it or uninstall it.",
        "hunt.noTarget": "No target yet",
        "hunt.howto": "Click on any other app window: Oblivion locks onto it here.",
        "hunt.running": "Running apps",
        "hunt.quit": "Quit",
        "hunt.forceQuit": "Force quit",

        "tools.subtitle": "Everything Revo has — and more",
        "tool.startup": "Startup manager",
        "tool.startup.d": "Launch agents & daemons that start with your Mac",
        "tool.junk": "Junk cleaner",
        "tool.junk.d": "Caches, logs, developer junk, old installers and the Trash",
        "tool.large": "Large files",
        "tool.large.d": "Find the biggest files hiding in your home folder",
        "tool.shredder": "Shredder",
        "tool.shredder.d": "Overwrite files with random data before deleting them",
        "tool.history": "History & privacy",
        "tool.history.d": "Recent items, Quick Look cache, clipboard and shell history",

        "common.scanning": "Scanning…",

        "startup.subtitle": "LaunchAgents and LaunchDaemons installed on this Mac",
        "startup.loginItems": "Login Items",
        "startup.empty": "No launch agents or daemons found.",
        "startup.atLogin": "At login",
        "startup.disabled": "Disabled",
        "startup.confirmTitle": "Remove this startup item?",
        "startup.confirmBody": "{name} will be moved to the Trash. Only remove system services if you know what they do.",
        "scope.userAgent": "User",
        "scope.globalAgent": "All users",
        "scope.daemon": "System daemon",

        "junk.subtitle": "Reclaim space safely — you choose every file, nothing personal is touched.",
        "junk.caches": "App caches",
        "junk.caches.d": "~/Library/Caches (rebuilt automatically by apps)",
        "junk.logs": "Logs",
        "junk.logs.d": "~/Library/Logs",
        "junk.dev": "Developer junk",
        "junk.dev.d": "Xcode DerivedData, device support and simulator caches",
        "junk.installers": "Old installers",
        "junk.installers.d": ".dmg / .pkg files in Downloads (moved to Trash)",
        "junk.trash": "Trash",
        "junk.trash.d": "Files waiting in the Trash",
        "junk.items": "{count} items",
        "junk.note": "Tip: quit open apps before cleaning their caches.",

        "large.subtitle": "Files over the selected size in your home folder",
        "large.scan": "Scan",
        "large.progress": "{count} files scanned…",
        "large.hint": "Pick a size and press Scan.",
        "large.none": "No files over that size.",
        "large.trash": "Move to Trash",

        "shred.subtitle": "Permanently destroy files — they skip the Trash.",
        "shred.drop": "Drop files or folders here",
        "shred.pick": "Choose files…",
        "shred.start": "Shred permanently",
        "shred.warning": "On SSDs (APFS) overwriting can't be fully guaranteed by any tool; keeping FileVault on is the strongest protection.",
        "shred.confirmTitle": "Shred permanently?",
        "shred.confirmBody": "{count} items will be overwritten and deleted. This cannot be undone.",
        "shred.done": "{count} files shredded.",

        "hist.subtitle": "Wipe traces of what you've been doing.",
        "hist.recents": "Recent items",
        "hist.recents.d": "Recent documents, apps and servers lists",
        "hist.quicklook": "Quick Look cache",
        "hist.quicklook.d": "Thumbnails of files you've previewed",
        "hist.clipboard": "Clipboard",
        "hist.clipboard.d": "Whatever is currently copied",
        "hist.shell": "Terminal history",
        "hist.shell.d": "zsh / bash command history",
        "hist.clean": "Clean selected",
        "hist.done": "{count} items cleared.",

        "set.subtitle": "Make Oblivion yours",
        "set.appearance": "Appearance",
        "set.appearance.d": "Dark, light or follow macOS",
        "set.system": "System",
        "set.light": "Light",
        "set.dark": "Dark",
        "set.language": "Language",
        "set.language.d": "Switch the interface language instantly",
        "set.confirm": "Ask before uninstalling",
        "set.confirm.d": "Show a confirmation before an app is removed",
        "set.fda": "Full Disk Access",
        "set.fda.on": "Granted — scans can see every leftover.",
        "set.fda.off": "Not granted — some leftovers may stay hidden.",
        "set.granted": "Granted",
        "set.notGranted": "Not granted",
        "set.version": "Version {version} · macOS",
        "set.about": "A modern uninstaller and cleaner for macOS, inspired by Revo Uninstaller Pro — built natively in SwiftUI for Apple Silicon and Intel Macs, with a deeper and safer leftover engine.",

        // 3.0
        "nav.systemMonitor": "System monitor",
        "rail.about": "About Oblivion",
        "rail.systemMonitor": "System monitor",
        "action.close": "Close",
        "action.clean": "Clean",
        "about.version": "Version {version}",
        "about.role": "Designer & developer of Oblivion",
        "about.repo": "Source code",
        "about.releases": "Releases",
        "about.whatsNew": "What's new in 3.0",
        "about.new1": "Live System Monitor: CPU, memory, temperature, network, disks, battery and the busiest processes",
        "about.new2": "Safer junk cleaner: nothing is pre-selected and every file is listed before anything is removed",
        "about.new3": "Leftovers are never ticked for you — one click selects only the exact matches if you want",
        "about.new4": "A confirmation with the exact list of files before every destructive action",
        "about.new5": "Startup items can be switched off and back on without deleting them",
        "about.new6": "Separate native builds for Apple Silicon and Intel Macs, each with its own temperature sensor reader",
        "about.new7": "Smoother animations that pause when the window is hidden, plus a Reduce motion option",
        "about.copyright": "© 2026 ANIL GÜL. All rights reserved.",
        "live.title": "Live",
        "live.cpu": "CPU",
        "live.memory": "Memory",
        "live.temp": "Temperature",
        "live.network": "Network",
        "live.disk": "Startup disk",
        "live.diskFree": "{free} free of {total}",
        "live.battery": "Battery {percent}%",
        "live.batteryCharging": "Charging · {percent}%",
        "live.open": "Open the system monitor",
        "sys.subtitle": "Live CPU, memory, temperature, network, disks and processes",
        "sys.live": "LIVE",
        "sys.activityMonitor": "Activity Monitor",
        "sys.cores": "{cores} cores",
        "sys.memUsed": "{used} of {total} in use",
        "sys.memNote": "App memory + wired + compressed",
        "sys.temperature": "Temperature",
        "sys.thermalState": "Thermal state: {state}",
        "sys.tempUnavailable": "No readable CPU sensor here; macOS's thermal state is shown instead.",
        "sys.tempSource": "Average of the CPU sensors",
        "sys.download": "Download",
        "sys.upload": "Upload",
        "sys.topProcesses": "Busiest processes",
        "sys.collecting": "Collecting data…",
        "sys.endTask": "End task",
        "sys.thisMac": "This Mac",
        "sys.model": "Model",
        "sys.arch": "Architecture",
        "sys.gpu": "Graphics",
        "sys.uptime": "Uptime",
        "sys.drives": "Drives",
        "sys.onAC": "On power adapter",
        "sys.timeLeft": "{time} left",
        "sys.health": "Health {health}%",
        "sys.cycles": "{cycles} cycles",
        "sys.thermal.nominal": "Normal",
        "sys.thermal.nominalShort": "Cool",
        "sys.thermal.fair": "Warm",
        "sys.thermal.fairShort": "Warm",
        "sys.thermal.serious": "Hot — performance may be reduced",
        "sys.thermal.seriousShort": "Hot",
        "sys.thermal.critical": "Critical — the Mac is slowing itself down",
        "sys.thermal.criticalShort": "Critical",
        "sys.protected": "{name} is a core macOS process and can't be ended from here.",
        "sys.endTitle": "End “{name}”?",
        "sys.endMany": "All {count} processes in this group will be asked to quit. Unsaved work in them may be lost.",
        "sys.endOne": "The process will be asked to quit. Unsaved work in it may be lost.",
        "sys.endFailed": "{name} couldn't be ended (it may belong to the system or another user).",
        "log.endTask": "Task ended",
        "log.launchOn": "Startup item switched on",
        "log.launchOff": "Startup item switched off",
        "dash.health": "System health",
        "dash.healthOpen": "Details",
        "junk.caches.note": "Apps rebuild their caches; the first launch afterwards can be a little slower.",
        "junk.dev.note": "Xcode re-creates these the next time you build.",
        "junk.installers.note": "Only disk images and installer packages — your other downloads are never listed.",
        "junk.trash.note": "Items in the Trash are deleted for good.",
        "junk.rescan": "Scan again",
        "junk.safety": "Nothing is selected for you. Open a category to see exactly which files and folders it holds, tick only what you want gone, then press Clean.",
        "junk.notScanned": "Not scanned yet",
        "junk.empty": "Nothing to clean here.",
        "junk.found": "{count} items · {size}",
        "junk.selectedOf": "{selected} of {count} selected",
        "junk.showItems": "Show items",
        "junk.hideItems": "Hide items",
        "junk.selectedTotal": "{count} items selected to clean",
        "junk.trashLocked": "Oblivion can't look inside the Trash without Full Disk Access. Ticking this empties the whole Trash through Finder.",
        "junk.trashAll": "Empty the whole Trash (via Finder)",
        "junk.confirmTitle": "Clean {count} items?",
        "junk.confirmBody": "{size} will be freed. Caches, logs, developer files and Trash items are deleted permanently (apps re-create caches and logs when needed); installers are moved to the Trash.",
        "junk.result": "{count} items removed · {size} freed",
        "startup.toggle": "Start automatically (switch it back on any time)",
        "startup.toggleFailed": "{name} couldn't be switched. macOS may be protecting it.",
        "startup.systemWide": "System-wide items can only be removed (needs your password).",
        "left.selectCertain": "Select exact matches",
        "left.confirmTitle": "Delete {count} leftovers?",
        "left.confirmBody": "They will be moved to the Trash ({size}), so you can still restore them. Installer receipts are forgotten with pkgutil (needs your password).",
        "mon.confirmTitle": "Remove {count} traced items?",
        "mon.confirmBody": "Files and folders go to the Trash. Installer receipts are forgotten with pkgutil (needs your password).",
        "br.confirmTitle": "Remove “{name}”?",
        "br.confirmBody": "The extension folder will be moved to the Trash. Quit {browser} first, otherwise it may restore the extension.",
        "large.confirmTitle": "Move {count} files to the Trash?",
        "large.confirmBody": "{size} will be moved to the Trash. You can restore them from there until you empty it.",
        "hist.confirmTitle": "Clear {count} items?",
        "hist.confirmBody": "This can't be undone.",
        "set.livePanel": "Live system panel",
        "set.livePanel.d": "CPU, memory, temperature and network on the right (on wide windows)",
        "set.motion": "Reduce motion",
        "set.motion.d": "Turn off decorative, continuously running animations",
        "set.aboutOpen": "About Oblivion",
        "tool.sysmon.d": "Live CPU, memory, temperature, network and processes",
        "common.selected": "{count} selected",
        "junk.tickHint": "Tick the items you want to remove",
    ]

    // MARK: Turkish

    static let tr: [String: String] = [

        "nav.dashboard": "Panel",
        "nav.apps": "Tüm uygulamalar",
        "nav.store": "App Store uygulamaları",
        "nav.monitor": "İzlenen kurulumlar",
        "nav.browser": "Tarayıcı eklentileri",
        "nav.logs": "Günlük veritabanı",
        "nav.hunter": "Avcı kipi",
        "nav.tools": "Araçlar",
        "nav.settings": "Ayarlar",

        "rail.theme": "Tema (koyu / açık / sistem)",
        "rail.language": "Dil (TR / EN)",

        "action.uninstall": "Kaldır",
        "action.force": "Zorla kaldır",
        "action.more": "Diğer komutlar",
        "action.hint": "Listeden bir uygulama seç",
        "action.refresh": "Yenile",
        "action.cancel": "İptal",
        "action.ok": "Tamam",
        "action.open": "Aç",
        "action.remove": "Kaldır",
        "action.selectAll": "Tümünü seç",
        "action.selectNone": "Hiçbiri",
        "action.skip": "Atla",

        "cmd.open": "Uygulamayı aç",
        "cmd.reveal": "Finder'da göster",
        "cmd.contents": "Paket içeriğini göster",
        "cmd.info": "Bilgi al",
        "cmd.copy": "Ayrıntıları kopyala",
        "cmd.web": "Web'de ara",

        "col.app": "Uygulama",
        "col.size": "Boyut",
        "col.version": "Sürüm",
        "col.arch": "Mimari",
        "col.installed": "Kurulum",
        "col.lastUsed": "Son açılış",
        "col.source": "Kaynak",
        "arch.universal": "Evrensel",

        "apps.subtitle": "{count} uygulama · {size}",
        "apps.search": "Uygulama veya paket kimliği ara…",
        "apps.loading": "Kurulu uygulamalar okunuyor…",
        "apps.empty": "Aramana uyan uygulama yok.",
        "apps.emptyStore": "Mac App Store uygulaması bulunamadı.",
        "desc.empty": "Ayrıntıları burada görmek için bir uygulama seç.",

        "confirm.title": "Bu uygulama kaldırılsın mı?",
        "confirm.message": "“{name}” Çöp Sepeti'ne taşınacak, ardından Oblivion kalıntıları tarayıp sana gösterecek.",
        "error.title": "Bir sorun oluştu",
        "error.removeFailed": "Uygulama Çöp Sepeti'ne taşınamadı. macOS izin istediyse lütfen izin verip tekrar dene.",

        "work.quitting": "Uygulama kapatılıyor ve Çöp Sepeti'ne taşınıyor…",
        "work.scanning": "Library klasörlerinde kalıntılar taranıyor…",
        "work.removing": "Seçilen kalıntılar siliniyor…",

        "left.title": "Kalıntılar bulundu",
        "left.subtitle": "{name} · {count} öğe",
        "left.info": "Geride kalanları gözden geçir. Hiçbir şey senin yerine seçilmez — gidecekleri işaretle ya da uygulamanın paket kimliğini taşıyanlar için “Kesin olanları seç”i kullan. Her şey Çöp Sepeti'ne gider, geri alabilirsin. 🔒 olanlar parolanı ister.",
        "left.selected": "{count} seçili · {size}",
        "left.remove": "Seçilenleri sil",
        "left.receipt": "Kurulum makbuzu (pkgutil)",
        "left.admin": "Yönetici parolası gerektirir",
        "conf.high": "Kesin",
        "conf.medium": "Muhtemel",
        "conf.low": "Olası",

        "done.title": "Tertemiz!",
        "done.freed": "Boşaltılan alan",
        "done.items": "Kaldırılan öğe",
        "done.back": "Listeye dön",

        "force.title": "Zorla kaldır",
        "force.subtitle": "Bir uygulamanın izlerini derinlemesine tara — silinmiş ya da bozuk olsa bile.",
        "force.placeholder": "Uygulama adı veya paket kimliği (ör. Spotify veya com.spotify.client)",
        "force.hint": "İpucu: bir uygulamayı bu pencereye sürükle, otomatik doldurulsun.",
        "force.scan": "Tara ve kaldır",

        "dash.subtitle": "Mac'ine tek bakışta göz at",
        "dash.apps": "Kurulu uygulama",
        "dash.footprint": "Toplam uygulama boyutu",
        "dash.measuring": "Boyutlar ölçülüyor…",
        "dash.launchItems": "Başlangıç öğesi",
        "dash.freeSpace": "Boş disk alanı",
        "dash.quick": "Hızlı işlemler",
        "dash.largest": "En büyük uygulamalar",
        "dash.activity": "Son etkinlik",
        "dash.allLogs": "Tüm kayıtlar",
        "dash.noActivity": "Kaldırma ve temizleme geçmişin burada görünecek.",

        "fda.title": "Oblivion'a Tam Disk Erişimi ver",
        "fda.body": "Bu izin olmadan bazı kalıntılar (Containers, Mail, Safari verileri…) taramada görünmez.",
        "fda.open": "Ayarları aç",

        "right.system": "Sistem",
        "right.chip": "Çip",
        "right.memory": "Bellek",
        "right.activity": "Son etkinlik",

        "mon.subtitle": "Bir kurulumu izle, sonra eklediği her şeyi kaldır.",
        "mon.step1": "Mac'inin taban anlık görüntüsünü al",
        "mon.step2": "İzlemek istediğin programı kur (veya çalıştır)",
        "mon.step3": "Karşılaştır — Oblivion eklenen her şeyi listeler",
        "mon.baseline": "Taban al",
        "mon.compare": "Karşılaştır",
        "mon.baselineAt": "Taban: {date}",
        "mon.ready": "Taban hazır. Bir şey kur, sonra Karşılaştır'a bas.",
        "mon.noBaseline": "Önce bir taban anlık görüntüsü al.",
        "mon.noChanges": "Tabandan beri yeni bir şey eklenmemiş.",
        "mon.found": "Tabandan beri {count} yeni öğe",
        "mon.remove": "Seçilenleri kaldır",
        "mon.kind.app": "Uygulama",
        "mon.kind.folder": "Klasör",
        "mon.kind.preferences": "Tercihler",
        "mon.kind.launchItem": "Başlangıç öğesi",
        "mon.kind.receipt": "Makbuz",

        "br.subtitle": "Chrome, Edge, Brave, Arc, Vivaldi, Opera, Firefox ve Safari",
        "br.note": "Bir eklentiyi kaldırmadan önce tarayıcıyı kapat. Senkronize eklentiler tarayıcı hesabından geri gelebilir.",
        "br.loading": "Tarayıcı eklentileri aranıyor…",
        "br.empty": "Tarayıcı eklentisi bulunamadı.",
        "br.managedBySafari": "Uygulamasını kaldır",

        "logs.subtitle": "Oblivion'un bu Mac'te yaptığı her şey",
        "logs.clear": "Günlüğü temizle",
        "logs.clearConfirm": "Tüm etkinlik günlüğü temizlensin mi?",

        "log.uninstalled": "Kaldırıldı",
        "log.forced": "Zorla kaldırma",
        "log.leftovers": "Kalıntılar silindi",
        "log.junk": "Gereksizler temizlendi",
        "log.extension": "Eklenti kaldırıldı",
        "log.shred": "Dosyalar parçalandı",
        "log.history": "Geçmiş temizlendi",
        "log.baseline": "Taban alındı",
        "log.monitorRemoved": "İzlenen öğeler kaldırıldı",
        "log.launchItem": "Başlangıç öğesi kaldırıldı",
        "log.largeFiles": "Büyük dosyalar çöpe atıldı",

        "hunt.subtitle": "Çalışan herhangi bir uygulamayı hedefle — kapat, bul ya da kaldır.",
        "hunt.noTarget": "Henüz hedef yok",
        "hunt.howto": "Başka bir uygulamanın penceresine tıkla: Oblivion onu burada hedefe kilitler.",
        "hunt.running": "Çalışan uygulamalar",
        "hunt.quit": "Kapat",
        "hunt.forceQuit": "Zorla kapat",

        "tools.subtitle": "Revo'da ne varsa — fazlasıyla",
        "tool.startup": "Başlangıç yöneticisi",
        "tool.startup.d": "Mac'inle birlikte açılan LaunchAgent ve daemon'lar",
        "tool.junk": "Gereksiz dosya temizleyici",
        "tool.junk.d": "Önbellekler, kayıtlar, geliştirici çöpü, eski kurulum dosyaları ve Çöp Sepeti",
        "tool.large": "Büyük dosyalar",
        "tool.large.d": "Ana klasöründe saklanan en büyük dosyaları bul",
        "tool.shredder": "Kurtarılamaz silme",
        "tool.shredder.d": "Dosyaları silmeden önce rastgele veriyle üzerine yaz",
        "tool.history": "Geçmiş ve gizlilik",
        "tool.history.d": "Son öğeler, Quick Look önbelleği, pano ve terminal geçmişi",

        "common.scanning": "Taranıyor…",

        "startup.subtitle": "Bu Mac'te kurulu LaunchAgent ve LaunchDaemon'lar",
        "startup.loginItems": "Giriş öğeleri",
        "startup.empty": "LaunchAgent veya daemon bulunamadı.",
        "startup.atLogin": "Girişte",
        "startup.disabled": "Devre dışı",
        "startup.confirmTitle": "Bu başlangıç öğesi kaldırılsın mı?",
        "startup.confirmBody": "{name} Çöp Sepeti'ne taşınacak. Sistem servislerini yalnızca ne işe yaradıklarını biliyorsan kaldır.",
        "scope.userAgent": "Kullanıcı",
        "scope.globalAgent": "Tüm kullanıcılar",
        "scope.daemon": "Sistem servisi",

        "junk.subtitle": "Güvenle yer aç — her dosyayı sen seçersin, kişisel hiçbir şeye dokunulmaz.",
        "junk.caches": "Uygulama önbellekleri",
        "junk.caches.d": "~/Library/Caches (uygulamalar otomatik yeniden oluşturur)",
        "junk.logs": "Kayıt dosyaları",
        "junk.logs.d": "~/Library/Logs",
        "junk.dev": "Geliştirici çöpü",
        "junk.dev.d": "Xcode DerivedData, cihaz desteği ve simülatör önbellekleri",
        "junk.installers": "Eski kurulum dosyaları",
        "junk.installers.d": "İndirilenler'deki .dmg / .pkg dosyaları (Çöp Sepeti'ne taşınır)",
        "junk.trash": "Çöp Sepeti",
        "junk.trash.d": "Çöp Sepeti'nde bekleyen dosyalar",
        "junk.items": "{count} öğe",
        "junk.note": "İpucu: önbelleklerini temizlemeden önce açık uygulamaları kapat.",

        "large.subtitle": "Ana klasöründe seçilen boyutun üzerindeki dosyalar",
        "large.scan": "Tara",
        "large.progress": "{count} dosya tarandı…",
        "large.hint": "Bir boyut seç ve Tara'ya bas.",
        "large.none": "Bu boyutun üzerinde dosya yok.",
        "large.trash": "Çöp Sepeti'ne taşı",

        "shred.subtitle": "Dosyaları kalıcı olarak yok et — Çöp Sepeti'ne gitmez.",
        "shred.drop": "Dosya veya klasörleri buraya bırak",
        "shred.pick": "Dosya seç…",
        "shred.start": "Kalıcı olarak parçala",
        "shred.warning": "SSD'lerde (APFS) üzerine yazma hiçbir araçla tam garanti edilemez; en güçlü koruma FileVault'u açık tutmaktır.",
        "shred.confirmTitle": "Kalıcı olarak parçalansın mı?",
        "shred.confirmBody": "{count} öğenin üzerine yazılıp silinecek. Bu işlem geri alınamaz.",
        "shred.done": "{count} dosya parçalandı.",

        "hist.subtitle": "Yaptıklarının izlerini sil.",
        "hist.recents": "Son öğeler",
        "hist.recents.d": "Son belgeler, uygulamalar ve sunucular listeleri",
        "hist.quicklook": "Quick Look önbelleği",
        "hist.quicklook.d": "Önizlediğin dosyaların küçük resimleri",
        "hist.clipboard": "Pano",
        "hist.clipboard.d": "Şu an kopyalanmış olan içerik",
        "hist.shell": "Terminal geçmişi",
        "hist.shell.d": "zsh / bash komut geçmişi",
        "hist.clean": "Seçilenleri temizle",
        "hist.done": "{count} öğe temizlendi.",

        "set.subtitle": "Oblivion'u kendine göre ayarla",
        "set.appearance": "Görünüm",
        "set.appearance.d": "Koyu, açık ya da macOS'u takip et",
        "set.system": "Sistem",
        "set.light": "Açık",
        "set.dark": "Koyu",
        "set.language": "Dil",
        "set.language.d": "Arayüz dilini anında değiştir",
        "set.confirm": "Kaldırmadan önce sor",
        "set.confirm.d": "Bir uygulama kaldırılmadan önce onay göster",
        "set.fda": "Tam Disk Erişimi",
        "set.fda.on": "Verildi — taramalar her kalıntıyı görebilir.",
        "set.fda.off": "Verilmedi — bazı kalıntılar gizli kalabilir.",
        "set.granted": "Verildi",
        "set.notGranted": "Verilmedi",
        "set.version": "Sürüm {version} · macOS",
        "set.about": "macOS için modern bir kaldırıcı ve temizleyici. Revo Uninstaller Pro'dan ilham alındı; Apple Silicon ve Intel Mac'ler için SwiftUI ile yerel olarak, daha derin ve daha güvenli bir kalıntı motoruyla yazıldı.",

        // 3.0
        "nav.systemMonitor": "Sistem izleyici",
        "rail.about": "Oblivion hakkında",
        "rail.systemMonitor": "Sistem izleyici",
        "action.close": "Kapat",
        "action.clean": "Temizle",
        "about.version": "Sürüm {version}",
        "about.role": "Oblivion'un tasarımcısı ve geliştiricisi",
        "about.repo": "Kaynak kodu",
        "about.releases": "Sürümler",
        "about.whatsNew": "3.0'da neler yeni",
        "about.new1": "Canlı Sistem İzleyici: işlemci, bellek, sıcaklık, ağ, diskler, pil ve en çok kaynak kullanan işlemler",
        "about.new2": "Daha güvenli gereksiz dosya temizleyici: hiçbir şey önceden seçilmez, silmeden önce her dosya tek tek listelenir",
        "about.new3": "Kalıntılar asla senin yerine işaretlenmez — istersen tek tıkla yalnızca kesin eşleşmeler seçilir",
        "about.new4": "Her silme işleminden önce, etkilenecek dosyaların tam listesiyle onay",
        "about.new5": "Başlangıç öğeleri silinmeden kapatılıp yeniden açılabilir",
        "about.new6": "Apple Silicon ve Intel Mac'ler için ayrı yerel derlemeler; her biri kendi sıcaklık sensörü okuyucusuyla",
        "about.new7": "Pencere gizliyken duran daha akıcı animasyonlar ve “Hareketi azalt” seçeneği",
        "about.copyright": "© 2026 ANIL GÜL. Tüm hakları saklıdır.",
        "live.title": "Canlı",
        "live.cpu": "İşlemci",
        "live.memory": "Bellek",
        "live.temp": "Sıcaklık",
        "live.network": "Ağ",
        "live.disk": "Başlangıç diski",
        "live.diskFree": "{total} içinde {free} boş",
        "live.battery": "Pil %{percent}",
        "live.batteryCharging": "Şarj oluyor · %{percent}",
        "live.open": "Sistem izleyiciyi aç",
        "sys.subtitle": "İşlemci, bellek, sıcaklık, ağ, diskler ve işlemler — canlı",
        "sys.live": "CANLI",
        "sys.activityMonitor": "Etkinlik Monitörü",
        "sys.cores": "{cores} çekirdek",
        "sys.memUsed": "{total} belleğin {used} kadarı kullanımda",
        "sys.memNote": "Uygulama + kalıcı + sıkıştırılmış bellek",
        "sys.temperature": "Sıcaklık",
        "sys.thermalState": "Isıl durum: {state}",
        "sys.tempUnavailable": "Okunabilir bir işlemci sensörü yok; bunun yerine macOS'un ısıl durumu gösteriliyor.",
        "sys.tempSource": "İşlemci sensörlerinin ortalaması",
        "sys.download": "İndirme",
        "sys.upload": "Yükleme",
        "sys.topProcesses": "En yoğun işlemler",
        "sys.collecting": "Veriler toplanıyor…",
        "sys.endTask": "Görevi sonlandır",
        "sys.thisMac": "Bu Mac",
        "sys.model": "Model",
        "sys.arch": "Mimari",
        "sys.gpu": "Grafik",
        "sys.uptime": "Açık kalma süresi",
        "sys.drives": "Diskler",
        "sys.onAC": "Güç adaptörüne bağlı",
        "sys.timeLeft": "{time} kaldı",
        "sys.health": "Sağlık %{health}",
        "sys.cycles": "{cycles} döngü",
        "sys.thermal.nominal": "Normal",
        "sys.thermal.nominalShort": "Serin",
        "sys.thermal.fair": "Ilık",
        "sys.thermal.fairShort": "Ilık",
        "sys.thermal.serious": "Sıcak — performans düşebilir",
        "sys.thermal.seriousShort": "Sıcak",
        "sys.thermal.critical": "Kritik — Mac kendini yavaşlatıyor",
        "sys.thermal.criticalShort": "Kritik",
        "sys.protected": "{name} temel bir macOS işlemi; buradan sonlandırılamaz.",
        "sys.endTitle": "“{name}” sonlandırılsın mı?",
        "sys.endMany": "Bu gruptaki {count} işlemin tümünden kapanması istenecek. Kaydedilmemiş çalışmalar kaybolabilir.",
        "sys.endOne": "İşlemden kapanması istenecek. Kaydedilmemiş çalışmalar kaybolabilir.",
        "sys.endFailed": "{name} sonlandırılamadı (sisteme ya da başka bir kullanıcıya ait olabilir).",
        "log.endTask": "Görev sonlandırıldı",
        "log.launchOn": "Başlangıç öğesi açıldı",
        "log.launchOff": "Başlangıç öğesi kapatıldı",
        "dash.health": "Sistem sağlığı",
        "dash.healthOpen": "Ayrıntılar",
        "junk.caches.note": "Uygulamalar önbelleklerini yeniden oluşturur; sonraki ilk açılış biraz yavaş olabilir.",
        "junk.dev.note": "Xcode bunları bir sonraki derlemede yeniden oluşturur.",
        "junk.installers.note": "Yalnızca disk görüntüleri ve kurulum paketleri — diğer indirdiklerin asla listelenmez.",
        "junk.trash.note": "Çöp Sepeti'ndeki öğeler kalıcı olarak silinir.",
        "junk.rescan": "Yeniden tara",
        "junk.safety": "Hiçbir şey senin yerine seçilmez. Bir kategoriyi açıp içindeki dosya ve klasörleri tek tek gör, yalnızca silinmesini istediklerini işaretle, sonra Temizle'ye bas.",
        "junk.notScanned": "Henüz taranmadı",
        "junk.empty": "Burada temizlenecek bir şey yok.",
        "junk.found": "{count} öğe · {size}",
        "junk.selectedOf": "{count} öğeden {selected} seçili",
        "junk.showItems": "Öğeleri göster",
        "junk.hideItems": "Öğeleri gizle",
        "junk.selectedTotal": "Temizlenmek üzere {count} öğe seçili",
        "junk.trashLocked": "Tam Disk Erişimi olmadan Oblivion Çöp Sepeti'nin içini göremez. Bunu işaretlersen tüm Çöp Sepeti Finder üzerinden boşaltılır.",
        "junk.trashAll": "Tüm Çöp Sepeti'ni boşalt (Finder ile)",
        "junk.confirmTitle": "{count} öğe temizlensin mi?",
        "junk.confirmBody": "{size} yer açılacak. Önbellek, kayıt, geliştirici dosyaları ve Çöp Sepeti öğeleri kalıcı olarak silinir (uygulamalar gerektiğinde önbellek ve kayıtları yeniden oluşturur); kurulum dosyaları Çöp Sepeti'ne taşınır.",
        "junk.result": "{count} öğe silindi · {size} yer açıldı",
        "startup.toggle": "Otomatik başlat (istediğin zaman yeniden açabilirsin)",
        "startup.toggleFailed": "{name} değiştirilemedi. macOS onu koruyor olabilir.",
        "startup.systemWide": "Sistem genelindeki öğeler yalnızca kaldırılabilir (parolanı ister).",
        "left.selectCertain": "Kesin olanları seç",
        "left.confirmTitle": "{count} kalıntı silinsin mi?",
        "left.confirmBody": "Çöp Sepeti'ne taşınacaklar ({size}), yani hâlâ geri alabilirsin. Kurulum makbuzları pkgutil ile unutulur (parolanı ister).",
        "mon.confirmTitle": "İzlenen {count} öğe kaldırılsın mı?",
        "mon.confirmBody": "Dosya ve klasörler Çöp Sepeti'ne gider. Kurulum makbuzları pkgutil ile unutulur (parolanı ister).",
        "br.confirmTitle": "“{name}” kaldırılsın mı?",
        "br.confirmBody": "Eklenti klasörü Çöp Sepeti'ne taşınacak. Önce {browser} tarayıcısını kapat, yoksa eklentiyi geri yükleyebilir.",
        "large.confirmTitle": "{count} dosya Çöp Sepeti'ne taşınsın mı?",
        "large.confirmBody": "{size} Çöp Sepeti'ne taşınacak. Sepeti boşaltana kadar oradan geri alabilirsin.",
        "hist.confirmTitle": "{count} öğe temizlensin mi?",
        "hist.confirmBody": "Bu işlem geri alınamaz.",
        "set.livePanel": "Canlı sistem paneli",
        "set.livePanel.d": "Sağda işlemci, bellek, sıcaklık ve ağ (geniş pencerelerde)",
        "set.motion": "Hareketi azalt",
        "set.motion.d": "Sürekli çalışan süs animasyonlarını kapat",
        "set.aboutOpen": "Oblivion hakkında",
        "tool.sysmon.d": "Canlı işlemci, bellek, sıcaklık, ağ ve işlemler",
        "common.selected": "{count} seçili",
        "junk.tickHint": "Silmek istediğin öğeleri işaretle",
    ]
}
