import Foundation
import SwiftUI

/// Live Turkish / English localization (same model as the Windows version).
final class Loc: ObservableObject {
    @Published var lang: String = "tr" {
        didSet { UserDefaults.standard.set(lang, forKey: "oblivion.lang") }
    }

    init() {
        if let saved = UserDefaults.standard.string(forKey: "oblivion.lang") {
            lang = saved
        } else {
            lang = (Locale.preferredLanguages.first ?? "tr").hasPrefix("tr") ? "tr" : "en"
        }
    }

    var isTurkish: Bool { lang == "tr" }

    func toggle() { lang = isTurkish ? "en" : "tr" }

    subscript(_ key: String) -> String {
        (isTurkish ? Loc.tr[key] : Loc.en[key]) ?? Loc.en[key] ?? key
    }

    /// Lookup with `{placeholder}` substitution.
    func t(_ key: String, _ args: [String: String]) -> String {
        var text = self[key]
        for (name, value) in args {
            text = text.replacingOccurrences(of: "{\(name)}", with: value)
        }
        return text
    }

    // MARK: English

    static let en: [String: String] = [
        "brand.by": "signed by ANIL GÜL",
        "brand.made": "Designed & built by ANIL GÜL",

        "nav.dashboard": "Dashboard",
        "nav.apps": "All applications",
        "nav.store": "App Store apps",
        "nav.monitor": "Monitored installs",
        "nav.browser": "Browser extensions",
        "nav.logs": "Logs database",
        "nav.hunter": "Hunter mode",
        "nav.tools": "Tools",
        "nav.settings": "Settings",

        "rail.theme": "Theme (dark / light / system)",
        "rail.language": "Language (TR / EN)",

        "action.uninstall": "Uninstall",
        "action.force": "Force uninstall",
        "action.more": "Other commands",
        "action.hint": "Select an app from the list",
        "action.refresh": "Refresh",
        "action.cancel": "Cancel",
        "action.ok": "OK",
        "action.open": "Open",
        "action.remove": "Remove",
        "action.selectAll": "Select all",
        "action.selectNone": "None",
        "action.skip": "Skip",

        "cmd.open": "Open app",
        "cmd.reveal": "Show in Finder",
        "cmd.contents": "Show package contents",
        "cmd.info": "Get info",
        "cmd.copy": "Copy details",
        "cmd.web": "Search the web",

        "col.app": "Application",
        "col.size": "Size",
        "col.version": "Version",
        "col.arch": "Architecture",
        "col.installed": "Installed",
        "col.lastUsed": "Last opened",
        "col.source": "Source",
        "arch.universal": "Universal",

        "apps.subtitle": "{count} apps · {size}",
        "apps.search": "Search apps or bundle IDs…",
        "apps.loading": "Reading installed applications…",
        "apps.empty": "No applications match your search.",
        "apps.emptyStore": "No Mac App Store apps found.",
        "desc.empty": "Select an application to see its details here.",

        "confirm.title": "Uninstall this app?",
        "confirm.message": "“{name}” will be moved to the Trash, then Oblivion will scan for leftovers so you can review them.",
        "error.title": "Something went wrong",
        "error.removeFailed": "The app couldn't be moved to the Trash. If macOS asked for permission, please allow it and try again.",

        "work.quitting": "Closing the app and moving it to the Trash…",
        "work.scanning": "Scanning Library folders for leftovers…",
        "work.removing": "Removing selected leftovers…",

        "left.title": "Leftovers found",
        "left.subtitle": "{name} · {count} items",
        "left.info": "Review what was left behind. Exact matches are pre-selected; everything goes to the Trash so it can be restored. 🔒 items need your password.",
        "left.selected": "{count} selected · {size}",
        "left.remove": "Delete selected",
        "left.receipt": "Installer receipt (pkgutil)",
        "left.admin": "Requires administrator password",
        "conf.high": "Exact",
        "conf.medium": "Likely",
        "conf.low": "Possible",

        "done.title": "All clean!",
        "done.freed": "Space freed",
        "done.items": "Items removed",
        "done.back": "Back to the list",

        "force.title": "Force uninstall",
        "force.subtitle": "Deep-scan for an app's traces — even if it's already deleted or broken.",
        "force.placeholder": "App name or bundle ID (e.g. Spotify or com.spotify.client)",
        "force.hint": "Tip: drag an app onto this window to fill it in automatically.",
        "force.scan": "Scan & remove",

        "dash.subtitle": "Your Mac at a glance",
        "dash.apps": "Installed apps",
        "dash.footprint": "Total app size",
        "dash.measuring": "Measuring sizes…",
        "dash.launchItems": "Startup items",
        "dash.freeSpace": "Free disk space",
        "dash.quick": "Quick actions",
        "dash.largest": "Largest applications",
        "dash.activity": "Recent activity",
        "dash.allLogs": "All logs",
        "dash.noActivity": "Your uninstall and cleanup history will appear here.",

        "fda.title": "Give Oblivion Full Disk Access",
        "fda.body": "Without it, some leftovers (containers, Mail, Safari data…) stay hidden from the scan.",
        "fda.open": "Open settings",

        "right.system": "System",
        "right.chip": "Chip",
        "right.memory": "Memory",
        "right.disk": "Free space",
        "right.diskOf": "of {total}",
        "right.activity": "Recent activity",
        "right.developer": "Developer",

        "mon.subtitle": "Trace an installation, then remove everything it added.",
        "mon.step1": "Take a baseline snapshot of your Mac",
        "mon.step2": "Install (or run) the program you want to trace",
        "mon.step3": "Compare — Oblivion lists everything that was added",
        "mon.baseline": "Take baseline",
        "mon.compare": "Compare",
        "mon.baselineAt": "Baseline: {date}",
        "mon.ready": "Baseline ready. Install something, then press Compare.",
        "mon.noBaseline": "Start by taking a baseline snapshot.",
        "mon.noChanges": "Nothing new was added since the baseline.",
        "mon.found": "{count} new items since the baseline",
        "mon.remove": "Remove selected",
        "mon.kind.app": "App",
        "mon.kind.folder": "Folder",
        "mon.kind.preferences": "Preferences",
        "mon.kind.launchItem": "Launch item",
        "mon.kind.receipt": "Receipt",

        "br.subtitle": "Chrome, Edge, Brave, Arc, Vivaldi, Opera, Firefox and Safari",
        "br.note": "Quit the browser before removing an extension. Synced extensions may come back from your browser account.",
        "br.loading": "Looking for browser extensions…",
        "br.empty": "No browser extensions found.",
        "br.managedBySafari": "Remove its app",

        "logs.subtitle": "Everything Oblivion has done on this Mac",
        "logs.clear": "Clear log",
        "logs.clearConfirm": "Clear the whole activity log?",

        "log.uninstalled": "Uninstalled",
        "log.forced": "Force uninstall",
        "log.leftovers": "Leftovers removed",
        "log.junk": "Junk cleaned",
        "log.extension": "Extension removed",
        "log.shred": "Files shredded",
        "log.history": "History cleared",
        "log.baseline": "Baseline taken",
        "log.monitorRemoved": "Traced items removed",
        "log.launchItem": "Startup item removed",
        "log.largeFiles": "Large files trashed",

        "hunt.subtitle": "Aim at any running app — quit it, find it or uninstall it.",
        "hunt.noTarget": "No target yet",
        "hunt.howto": "Click on any other app window: Oblivion locks onto it here.",
        "hunt.running": "Running apps",
        "hunt.quit": "Quit",
        "hunt.forceQuit": "Force quit",

        "tools.subtitle": "Everything Revo has — and more",
        "tool.startup": "Startup manager",
        "tool.startup.d": "Launch agents & daemons that start with your Mac",
        "tool.junk": "Junk cleaner",
        "tool.junk.d": "Caches, logs, developer junk, old installers and the Trash",
        "tool.large": "Large files",
        "tool.large.d": "Find the biggest files hiding in your home folder",
        "tool.shredder": "Shredder",
        "tool.shredder.d": "Overwrite files with random data before deleting them",
        "tool.history": "History & privacy",
        "tool.history.d": "Recent items, Quick Look cache, clipboard and shell history",

        "common.scanning": "Scanning…",

        "startup.subtitle": "LaunchAgents and LaunchDaemons installed on this Mac",
        "startup.loginItems": "Login Items",
        "startup.empty": "No launch agents or daemons found.",
        "startup.atLogin": "At login",
        "startup.disabled": "Disabled",
        "startup.confirmTitle": "Remove this startup item?",
        "startup.confirmBody": "{name} will be moved to the Trash. Only remove system services if you know what they do.",
        "scope.userAgent": "User",
        "scope.globalAgent": "All users",
        "scope.daemon": "System daemon",

        "junk.subtitle": "Reclaim space safely — nothing personal is touched.",
        "junk.caches": "App caches",
        "junk.caches.d": "~/Library/Caches (rebuilt automatically by apps)",
        "junk.logs": "Logs",
        "junk.logs.d": "~/Library/Logs",
        "junk.dev": "Developer junk",
        "junk.dev.d": "Xcode DerivedData, device support and simulator caches",
        "junk.installers": "Old installers",
        "junk.installers.d": ".dmg / .pkg files in Downloads (moved to Trash)",
        "junk.trash": "Trash",
        "junk.trash.d": "Empty the Trash",
        "junk.items": "{count} items",
        "junk.note": "Tip: quit open apps before cleaning their caches.",
        "junk.reclaimable": "Reclaimable",
        "junk.freed": "{size} freed",
        "junk.analyze": "Analyze",
        "junk.clean": "Clean now",

        "large.subtitle": "Files over the selected size in your home folder",
        "large.scan": "Scan",
        "large.progress": "{count} files scanned…",
        "large.hint": "Pick a size and press Scan.",
        "large.none": "No files over that size.",
        "large.trash": "Move to Trash",

        "shred.subtitle": "Permanently destroy files — they skip the Trash.",
        "shred.drop": "Drop files or folders here",
        "shred.pick": "Choose files…",
        "shred.start": "Shred permanently",
        "shred.warning": "On SSDs (APFS) overwriting can't be fully guaranteed by any tool; keeping FileVault on is the strongest protection.",
        "shred.confirmTitle": "Shred permanently?",
        "shred.confirmBody": "{count} items will be overwritten and deleted. This cannot be undone.",
        "shred.done": "{count} files shredded.",

        "hist.subtitle": "Wipe traces of what you've been doing.",
        "hist.recents": "Recent items",
        "hist.recents.d": "Recent documents, apps and servers lists",
        "hist.quicklook": "Quick Look cache",
        "hist.quicklook.d": "Thumbnails of files you've previewed",
        "hist.clipboard": "Clipboard",
        "hist.clipboard.d": "Whatever is currently copied",
        "hist.shell": "Terminal history",
        "hist.shell.d": "zsh / bash command history",
        "hist.clean": "Clean selected",
        "hist.done": "{count} items cleared.",

        "set.subtitle": "Make Oblivion yours",
        "set.appearance": "Appearance",
        "set.appearance.d": "Dark, light or follow macOS",
        "set.system": "System",
        "set.light": "Light",
        "set.dark": "Dark",
        "set.language": "Language",
        "set.language.d": "Switch the interface language instantly",
        "set.preselect": "Pre-select likely leftovers",
        "set.preselect.d": "Also tick folders named exactly like the app",
        "set.confirm": "Ask before uninstalling",
        "set.confirm.d": "Show a confirmation before an app is removed",
        "set.fda": "Full Disk Access",
        "set.fda.on": "Granted — scans can see every leftover.",
        "set.fda.off": "Not granted — some leftovers may stay hidden.",
        "set.granted": "Granted",
        "set.notGranted": "Not granted",
        "set.version": "Version {version} · macOS",
        "set.about": "A modern uninstaller and cleaner for macOS. Inspired by Revo Uninstaller Pro, rebuilt natively in SwiftUI for Apple Silicon — with a deeper, safer leftover engine.",
    ]

    // MARK: Turkish

    static let tr: [String: String] = [
        "brand.by": "ANIL GÜL imzasıyla",
        "brand.made": "ANIL GÜL tarafından tasarlandı ve geliştirildi",

        "nav.dashboard": "Panel",
        "nav.apps": "Tüm uygulamalar",
        "nav.store": "App Store uygulamaları",
        "nav.monitor": "İzlenen kurulumlar",
        "nav.browser": "Tarayıcı eklentileri",
        "nav.logs": "Günlük veritabanı",
        "nav.hunter": "Avcı kipi",
        "nav.tools": "Araçlar",
        "nav.settings": "Ayarlar",

        "rail.theme": "Tema (koyu / açık / sistem)",
        "rail.language": "Dil (TR / EN)",

        "action.uninstall": "Kaldır",
        "action.force": "Zorla kaldır",
        "action.more": "Diğer komutlar",
        "action.hint": "Listeden bir uygulama seç",
        "action.refresh": "Yenile",
        "action.cancel": "İptal",
        "action.ok": "Tamam",
        "action.open": "Aç",
        "action.remove": "Kaldır",
        "action.selectAll": "Tümünü seç",
        "action.selectNone": "Hiçbiri",
        "action.skip": "Atla",

        "cmd.open": "Uygulamayı aç",
        "cmd.reveal": "Finder'da göster",
        "cmd.contents": "Paket içeriğini göster",
        "cmd.info": "Bilgi al",
        "cmd.copy": "Ayrıntıları kopyala",
        "cmd.web": "Web'de ara",

        "col.app": "Uygulama",
        "col.size": "Boyut",
        "col.version": "Sürüm",
        "col.arch": "Mimari",
        "col.installed": "Kurulum",
        "col.lastUsed": "Son açılış",
        "col.source": "Kaynak",
        "arch.universal": "Evrensel",

        "apps.subtitle": "{count} uygulama · {size}",
        "apps.search": "Uygulama veya paket kimliği ara…",
        "apps.loading": "Kurulu uygulamalar okunuyor…",
        "apps.empty": "Aramana uyan uygulama yok.",
        "apps.emptyStore": "Mac App Store uygulaması bulunamadı.",
        "desc.empty": "Ayrıntıları burada görmek için bir uygulama seç.",

        "confirm.title": "Bu uygulama kaldırılsın mı?",
        "confirm.message": "“{name}” Çöp Sepeti'ne taşınacak, ardından Oblivion kalıntıları tarayıp sana gösterecek.",
        "error.title": "Bir sorun oluştu",
        "error.removeFailed": "Uygulama Çöp Sepeti'ne taşınamadı. macOS izin istediyse lütfen izin verip tekrar dene.",

        "work.quitting": "Uygulama kapatılıyor ve Çöp Sepeti'ne taşınıyor…",
        "work.scanning": "Library klasörlerinde kalıntılar taranıyor…",
        "work.removing": "Seçilen kalıntılar siliniyor…",

        "left.title": "Kalıntılar bulundu",
        "left.subtitle": "{name} · {count} öğe",
        "left.info": "Geride kalanları gözden geçir. Kesin eşleşmeler önceden seçili; her şey Çöp Sepeti'ne gider, geri alabilirsin. 🔒 olanlar parolanı ister.",
        "left.selected": "{count} seçili · {size}",
        "left.remove": "Seçilenleri sil",
        "left.receipt": "Kurulum makbuzu (pkgutil)",
        "left.admin": "Yönetici parolası gerektirir",
        "conf.high": "Kesin",
        "conf.medium": "Muhtemel",
        "conf.low": "Olası",

        "done.title": "Tertemiz!",
        "done.freed": "Boşaltılan alan",
        "done.items": "Kaldırılan öğe",
        "done.back": "Listeye dön",

        "force.title": "Zorla kaldır",
        "force.subtitle": "Bir uygulamanın izlerini derinlemesine tara — silinmiş ya da bozuk olsa bile.",
        "force.placeholder": "Uygulama adı veya paket kimliği (ör. Spotify veya com.spotify.client)",
        "force.hint": "İpucu: bir uygulamayı bu pencereye sürükle, otomatik doldurulsun.",
        "force.scan": "Tara ve kaldır",

        "dash.subtitle": "Mac'ine tek bakışta göz at",
        "dash.apps": "Kurulu uygulama",
        "dash.footprint": "Toplam uygulama boyutu",
        "dash.measuring": "Boyutlar ölçülüyor…",
        "dash.launchItems": "Başlangıç öğesi",
        "dash.freeSpace": "Boş disk alanı",
        "dash.quick": "Hızlı işlemler",
        "dash.largest": "En büyük uygulamalar",
        "dash.activity": "Son etkinlik",
        "dash.allLogs": "Tüm kayıtlar",
        "dash.noActivity": "Kaldırma ve temizleme geçmişin burada görünecek.",

        "fda.title": "Oblivion'a Tam Disk Erişimi ver",
        "fda.body": "Bu izin olmadan bazı kalıntılar (Containers, Mail, Safari verileri…) taramada görünmez.",
        "fda.open": "Ayarları aç",

        "right.system": "Sistem",
        "right.chip": "Çip",
        "right.memory": "Bellek",
        "right.disk": "Boş alan",
        "right.diskOf": "toplam {total}",
        "right.activity": "Son etkinlik",
        "right.developer": "Geliştirici",

        "mon.subtitle": "Bir kurulumu izle, sonra eklediği her şeyi kaldır.",
        "mon.step1": "Mac'inin taban anlık görüntüsünü al",
        "mon.step2": "İzlemek istediğin programı kur (veya çalıştır)",
        "mon.step3": "Karşılaştır — Oblivion eklenen her şeyi listeler",
        "mon.baseline": "Taban al",
        "mon.compare": "Karşılaştır",
        "mon.baselineAt": "Taban: {date}",
        "mon.ready": "Taban hazır. Bir şey kur, sonra Karşılaştır'a bas.",
        "mon.noBaseline": "Önce bir taban anlık görüntüsü al.",
        "mon.noChanges": "Tabandan beri yeni bir şey eklenmemiş.",
        "mon.found": "Tabandan beri {count} yeni öğe",
        "mon.remove": "Seçilenleri kaldır",
        "mon.kind.app": "Uygulama",
        "mon.kind.folder": "Klasör",
        "mon.kind.preferences": "Tercihler",
        "mon.kind.launchItem": "Başlangıç öğesi",
        "mon.kind.receipt": "Makbuz",

        "br.subtitle": "Chrome, Edge, Brave, Arc, Vivaldi, Opera, Firefox ve Safari",
        "br.note": "Bir eklentiyi kaldırmadan önce tarayıcıyı kapat. Senkronize eklentiler tarayıcı hesabından geri gelebilir.",
        "br.loading": "Tarayıcı eklentileri aranıyor…",
        "br.empty": "Tarayıcı eklentisi bulunamadı.",
        "br.managedBySafari": "Uygulamasını kaldır",

        "logs.subtitle": "Oblivion'un bu Mac'te yaptığı her şey",
        "logs.clear": "Günlüğü temizle",
        "logs.clearConfirm": "Tüm etkinlik günlüğü temizlensin mi?",

        "log.uninstalled": "Kaldırıldı",
        "log.forced": "Zorla kaldırma",
        "log.leftovers": "Kalıntılar silindi",
        "log.junk": "Gereksizler temizlendi",
        "log.extension": "Eklenti kaldırıldı",
        "log.shred": "Dosyalar parçalandı",
        "log.history": "Geçmiş temizlendi",
        "log.baseline": "Taban alındı",
        "log.monitorRemoved": "İzlenen öğeler kaldırıldı",
        "log.launchItem": "Başlangıç öğesi kaldırıldı",
        "log.largeFiles": "Büyük dosyalar çöpe atıldı",

        "hunt.subtitle": "Çalışan herhangi bir uygulamayı hedefle — kapat, bul ya da kaldır.",
        "hunt.noTarget": "Henüz hedef yok",
        "hunt.howto": "Başka bir uygulamanın penceresine tıkla: Oblivion onu burada hedefe kilitler.",
        "hunt.running": "Çalışan uygulamalar",
        "hunt.quit": "Kapat",
        "hunt.forceQuit": "Zorla kapat",

        "tools.subtitle": "Revo'da ne varsa — fazlasıyla",
        "tool.startup": "Başlangıç yöneticisi",
        "tool.startup.d": "Mac'inle birlikte açılan LaunchAgent ve daemon'lar",
        "tool.junk": "Gereksiz dosya temizleyici",
        "tool.junk.d": "Önbellekler, kayıtlar, geliştirici çöpü, eski kurulum dosyaları ve Çöp Sepeti",
        "tool.large": "Büyük dosyalar",
        "tool.large.d": "Ana klasöründe saklanan en büyük dosyaları bul",
        "tool.shredder": "Kurtarılamaz silme",
        "tool.shredder.d": "Dosyaları silmeden önce rastgele veriyle üzerine yaz",
        "tool.history": "Geçmiş ve gizlilik",
        "tool.history.d": "Son öğeler, Quick Look önbelleği, pano ve terminal geçmişi",

        "common.scanning": "Taranıyor…",

        "startup.subtitle": "Bu Mac'te kurulu LaunchAgent ve LaunchDaemon'lar",
        "startup.loginItems": "Giriş öğeleri",
        "startup.empty": "LaunchAgent veya daemon bulunamadı.",
        "startup.atLogin": "Girişte",
        "startup.disabled": "Devre dışı",
        "startup.confirmTitle": "Bu başlangıç öğesi kaldırılsın mı?",
        "startup.confirmBody": "{name} Çöp Sepeti'ne taşınacak. Sistem servislerini yalnızca ne işe yaradıklarını biliyorsan kaldır.",
        "scope.userAgent": "Kullanıcı",
        "scope.globalAgent": "Tüm kullanıcılar",
        "scope.daemon": "Sistem servisi",

        "junk.subtitle": "Güvenle yer aç — kişisel hiçbir şeye dokunulmaz.",
        "junk.caches": "Uygulama önbellekleri",
        "junk.caches.d": "~/Library/Caches (uygulamalar otomatik yeniden oluşturur)",
        "junk.logs": "Kayıt dosyaları",
        "junk.logs.d": "~/Library/Logs",
        "junk.dev": "Geliştirici çöpü",
        "junk.dev.d": "Xcode DerivedData, cihaz desteği ve simülatör önbellekleri",
        "junk.installers": "Eski kurulum dosyaları",
        "junk.installers.d": "İndirilenler'deki .dmg / .pkg dosyaları (Çöp Sepeti'ne taşınır)",
        "junk.trash": "Çöp Sepeti",
        "junk.trash.d": "Çöp Sepeti'ni boşalt",
        "junk.items": "{count} öğe",
        "junk.note": "İpucu: önbelleklerini temizlemeden önce açık uygulamaları kapat.",
        "junk.reclaimable": "Kazanılabilir alan",
        "junk.freed": "{size} boşaltıldı",
        "junk.analyze": "Çözümle",
        "junk.clean": "Şimdi temizle",

        "large.subtitle": "Ana klasöründe seçilen boyutun üzerindeki dosyalar",
        "large.scan": "Tara",
        "large.progress": "{count} dosya tarandı…",
        "large.hint": "Bir boyut seç ve Tara'ya bas.",
        "large.none": "Bu boyutun üzerinde dosya yok.",
        "large.trash": "Çöp Sepeti'ne taşı",

        "shred.subtitle": "Dosyaları kalıcı olarak yok et — Çöp Sepeti'ne gitmez.",
        "shred.drop": "Dosya veya klasörleri buraya bırak",
        "shred.pick": "Dosya seç…",
        "shred.start": "Kalıcı olarak parçala",
        "shred.warning": "SSD'lerde (APFS) üzerine yazma hiçbir araçla tam garanti edilemez; en güçlü koruma FileVault'u açık tutmaktır.",
        "shred.confirmTitle": "Kalıcı olarak parçalansın mı?",
        "shred.confirmBody": "{count} öğenin üzerine yazılıp silinecek. Bu işlem geri alınamaz.",
        "shred.done": "{count} dosya parçalandı.",

        "hist.subtitle": "Yaptıklarının izlerini sil.",
        "hist.recents": "Son öğeler",
        "hist.recents.d": "Son belgeler, uygulamalar ve sunucular listeleri",
        "hist.quicklook": "Quick Look önbelleği",
        "hist.quicklook.d": "Önizlediğin dosyaların küçük resimleri",
        "hist.clipboard": "Pano",
        "hist.clipboard.d": "Şu an kopyalanmış olan içerik",
        "hist.shell": "Terminal geçmişi",
        "hist.shell.d": "zsh / bash komut geçmişi",
        "hist.clean": "Seçilenleri temizle",
        "hist.done": "{count} öğe temizlendi.",

        "set.subtitle": "Oblivion'u kendine göre ayarla",
        "set.appearance": "Görünüm",
        "set.appearance.d": "Koyu, açık ya da macOS'u takip et",
        "set.system": "Sistem",
        "set.light": "Açık",
        "set.dark": "Koyu",
        "set.language": "Dil",
        "set.language.d": "Arayüz dilini anında değiştir",
        "set.preselect": "Muhtemel kalıntıları önceden seç",
        "set.preselect.d": "Uygulamayla birebir aynı adlı klasörleri de işaretle",
        "set.confirm": "Kaldırmadan önce sor",
        "set.confirm.d": "Bir uygulama kaldırılmadan önce onay göster",
        "set.fda": "Tam Disk Erişimi",
        "set.fda.on": "Verildi — taramalar her kalıntıyı görebilir.",
        "set.fda.off": "Verilmedi — bazı kalıntılar gizli kalabilir.",
        "set.granted": "Verildi",
        "set.notGranted": "Verilmedi",
        "set.version": "Sürüm {version} · macOS",
        "set.about": "macOS için modern bir kaldırıcı ve temizleyici. Revo Uninstaller Pro'dan ilham alındı; Apple Silicon için SwiftUI ile yerel olarak, daha derin ve daha güvenli bir kalıntı motoruyla yeniden yazıldı.",
    ]
}
